exports.gminy = [
{ gmina: 'Żukowo', woj: 'pomorskie' },
{ gmina: 'Zblewo', woj: 'pomorskie' },
{ gmina: 'Władysławowo', woj: 'pomorskie' },
{ gmina: 'Wicko', woj: 'pomorskie' },
{ gmina: 'Wejherowo', woj: 'pomorskie' },
{ gmina: 'Ustka', woj: 'pomorskie' },
{ gmina: 'Tuchomie', woj: 'pomorskie' },
{ gmina: 'Trzebielino', woj: 'pomorskie' },
{ gmina: 'Trąbki Wielkie', woj: 'pomorskie' },
{ gmina: 'Tczew', woj: 'pomorskie' },
{ gmina: 'Sztutowo', woj: 'pomorskie' },
{ gmina: 'Sztum', woj: 'pomorskie' },
{ gmina: 'Szemud', woj: 'pomorskie' },
{ gmina: 'Sulęczyno', woj: 'pomorskie' },
{ gmina: 'Suchy Dąb', woj: 'pomorskie' },
{ gmina: 'Subkowy', woj: 'pomorskie' },
{ gmina: 'Studzienice', woj: 'pomorskie' },
{ gmina: 'Stężyca', woj: 'pomorskie' },
{ gmina: 'Stegna', woj: 'pomorskie' },
{ gmina: 'Stary Targ', woj: 'pomorskie' },
{ gmina: 'Stary Dzierzgoń', woj: 'pomorskie' },
{ gmina: 'Starogard Gdański', woj: 'pomorskie' },
{ gmina: 'Stare Pole', woj: 'pomorskie' },
{ gmina: 'Stara Kiszewa', woj: 'pomorskie' },
{ gmina: 'Sopot', woj: 'pomorskie' },
{ gmina: 'Somonino', woj: 'pomorskie' },
{ gmina: 'Smołdzino', woj: 'pomorskie' },
{ gmina: 'Smętowo Graniczne', woj: 'pomorskie' },
{ gmina: 'Słupsk', woj: 'pomorskie' },
{ gmina: 'Skórcz', woj: 'pomorskie' },
{ gmina: 'Skarszewy', woj: 'pomorskie' },
{ gmina: 'Sierakowice', woj: 'pomorskie' },
{ gmina: 'Sadlinki', woj: 'pomorskie' },
{ gmina: 'Rzeczenica', woj: 'pomorskie' },
{ gmina: 'Ryjewo', woj: 'pomorskie' },
{ gmina: 'Rumia', woj: 'pomorskie' },
{ gmina: 'Reda', woj: 'pomorskie' },
{ gmina: 'Puck', woj: 'pomorskie' },
{ gmina: 'Pszczółki', woj: 'pomorskie' },
{ gmina: 'Przywidz', woj: 'pomorskie' },
{ gmina: 'Przodkowo', woj: 'pomorskie' },
{ gmina: 'Przechlewo', woj: 'pomorskie' },
{ gmina: 'Pruszcz Gdański', woj: 'pomorskie' },
{ gmina: 'Prabuty', woj: 'pomorskie' },
{ gmina: 'Potęgowo', woj: 'pomorskie' },
{ gmina: 'Pelplin', woj: 'pomorskie' },
{ gmina: 'Parchowo', woj: 'pomorskie' },
{ gmina: 'Ostaszewo', woj: 'pomorskie' },
{ gmina: 'Osiek', woj: 'pomorskie' },
{ gmina: 'Osieczna', woj: 'pomorskie' },
{ gmina: 'Nowy Staw', woj: 'pomorskie' },
{ gmina: 'Nowy Dwór Gdański', woj: 'pomorskie' },
{ gmina: 'Nowa Karczma', woj: 'pomorskie' },
{ gmina: 'Morzeszczyn', woj: 'pomorskie' },
{ gmina: 'Miłoradz', woj: 'pomorskie' },
{ gmina: 'Mikołajki Pomorskie', woj: 'pomorskie' },
{ gmina: 'Miastko', woj: 'pomorskie' },
{ gmina: 'Malbork', woj: 'pomorskie' },
{ gmina: 'Łęczyce', woj: 'pomorskie' },
{ gmina: 'Łeba', woj: 'pomorskie' },
{ gmina: 'Luzino', woj: 'pomorskie' },
{ gmina: 'Lubichowo', woj: 'pomorskie' },
{ gmina: 'Lipusz', woj: 'pomorskie' },
{ gmina: 'Lipnica', woj: 'pomorskie' },
{ gmina: 'Liniewo', woj: 'pomorskie' },
{ gmina: 'Linia', woj: 'pomorskie' },
{ gmina: 'Lichnowy', woj: 'pomorskie' },
{ gmina: 'Lębork', woj: 'pomorskie' },
{ gmina: 'Kwidzyn', woj: 'pomorskie' },
{ gmina: 'Krynica Morska', woj: 'pomorskie' },
{ gmina: 'Krokowa', woj: 'pomorskie' },
{ gmina: 'Kościerzyna', woj: 'pomorskie' },
{ gmina: 'Kosakowo', woj: 'pomorskie' },
{ gmina: 'Kołczygłowy', woj: 'pomorskie' },
{ gmina: 'Kolbudy', woj: 'pomorskie' },
{ gmina: 'Koczała', woj: 'pomorskie' },
{ gmina: 'Kobylnica', woj: 'pomorskie' },
{ gmina: 'Kępice', woj: 'pomorskie' },
{ gmina: 'Kartuzy', woj: 'pomorskie' },
{ gmina: 'Karsin', woj: 'pomorskie' },
{ gmina: 'Kaliska', woj: 'pomorskie' },
{ gmina: 'Jastarnia', woj: 'pomorskie' },
{ gmina: 'Hel', woj: 'pomorskie' },
{ gmina: 'Gniewino', woj: 'pomorskie' },
{ gmina: 'Gniew', woj: 'pomorskie' },
{ gmina: 'Główczyce', woj: 'pomorskie' },
{ gmina: 'Gdynia', woj: 'pomorskie' },
{ gmina: 'Gdańsk', woj: 'pomorskie' },
{ gmina: 'Gardeja', woj: 'pomorskie' },
{ gmina: 'Dzierzgoń', woj: 'pomorskie' },
{ gmina: 'Dziemiany', woj: 'pomorskie' },
{ gmina: 'Dębnica Kaszubska', woj: 'pomorskie' },
{ gmina: 'Debrzno', woj: 'pomorskie' },
{ gmina: 'Damnica', woj: 'pomorskie' },
{ gmina: 'Człuchów', woj: 'pomorskie' },
{ gmina: 'Czersk', woj: 'pomorskie' },
{ gmina: 'Czarne', woj: 'pomorskie' },
{ gmina: 'Czarna Woda', woj: 'pomorskie' },
{ gmina: 'Czarna Dąbrówka', woj: 'pomorskie' },
{ gmina: 'Chojnice', woj: 'pomorskie' },
{ gmina: 'Choczewo', woj: 'pomorskie' },
{ gmina: 'Chmielno', woj: 'pomorskie' },
{ gmina: 'Cewice', woj: 'pomorskie' },
{ gmina: 'Cedry Wielkie', woj: 'pomorskie' },
{ gmina: 'Bytów', woj: 'pomorskie' },
{ gmina: 'Brusy', woj: 'pomorskie' },
{ gmina: 'Borzytuchom', woj: 'pomorskie' },
{ gmina: 'Bobowo', woj: 'pomorskie' },
{ gmina: 'Żnin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Złotniki Kujawskie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Zławieś Wielka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Zbójno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Zbiczno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Zakrzewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Włocławek', woj: 'kujawsko-pomorskie' },
{ gmina: 'Więcbork', woj: 'kujawsko-pomorskie' },
{ gmina: 'Wielka Nieszawka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Wielgie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Wąpielsk', woj: 'kujawsko-pomorskie' },
{ gmina: 'Wąbrzeźno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Wąbrzeźno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Warlubie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Waganiec', woj: 'kujawsko-pomorskie' },
{ gmina: 'Unisław', woj: 'kujawsko-pomorskie' },
{ gmina: 'Tuchola', woj: 'kujawsko-pomorskie' },
{ gmina: 'Toruń', woj: 'kujawsko-pomorskie' },
{ gmina: 'Topólka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Tłuchowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Świekatowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Świedziebnia', woj: 'kujawsko-pomorskie' },
{ gmina: 'Świecie nad Osą', woj: 'kujawsko-pomorskie' },
{ gmina: 'Świecie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Śliwice', woj: 'kujawsko-pomorskie' },
{ gmina: 'Szubin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Strzelno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Stolno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Sośno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Solec Kujawski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Skrwilno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Skępe', woj: 'kujawsko-pomorskie' },
{ gmina: 'Sicienko', woj: 'kujawsko-pomorskie' },
{ gmina: 'Sępólno Krajeńskie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Sadki', woj: 'kujawsko-pomorskie' },
{ gmina: 'Rypin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Rojewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Rogóźno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Rogowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Radzyń Chełmiński', woj: 'kujawsko-pomorskie' },
{ gmina: 'Radziejów', woj: 'kujawsko-pomorskie' },
{ gmina: 'Radomin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Raciążek', woj: 'kujawsko-pomorskie' },
{ gmina: 'Pruszcz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Płużnica', woj: 'kujawsko-pomorskie' },
{ gmina: 'Piotrków Kujawski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Papowo Biskupie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Pakość', woj: 'kujawsko-pomorskie' },
{ gmina: 'Osięciny', woj: 'kujawsko-pomorskie' },
{ gmina: 'Osielsko', woj: 'kujawsko-pomorskie' },
{ gmina: 'Osiek', woj: 'kujawsko-pomorskie' },
{ gmina: 'Osie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Obrowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Nowe', woj: 'kujawsko-pomorskie' },
{ gmina: 'Nowa Wieś Wielka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Nieszawa', woj: 'kujawsko-pomorskie' },
{ gmina: 'Nakło nad Notecią', woj: 'kujawsko-pomorskie' },
{ gmina: 'Mrocza', woj: 'kujawsko-pomorskie' },
{ gmina: 'Mogilno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Łysomice', woj: 'kujawsko-pomorskie' },
{ gmina: 'Łubianka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Łasin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Łabiszyn', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lubraniec', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lubiewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lubień Kujawski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lubicz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lubanie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lniano', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lisewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Lipno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Książki', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kruszwica', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kowalewo Pomorskie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kowal', woj: 'kujawsko-pomorskie' },
{ gmina: 'Koronowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Koneck', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kikół', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kijewo Królewskie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kęsowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kcynia', woj: 'kujawsko-pomorskie' },
{ gmina: 'Kamień Krajeński', woj: 'kujawsko-pomorskie' },
{ gmina: 'Jeżewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Jeziora Wielkie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Janowiec Wielkopolski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Janikowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Jabłonowo Pomorskie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Izbica Kujawska', woj: 'kujawsko-pomorskie' },
{ gmina: 'Inowrocław', woj: 'kujawsko-pomorskie' },
{ gmina: 'Gruta', woj: 'kujawsko-pomorskie' },
{ gmina: 'Grudziądz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Górzno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Gostycyn', woj: 'kujawsko-pomorskie' },
{ gmina: 'Golub-Dobrzyń', woj: 'kujawsko-pomorskie' },
{ gmina: 'Gniewkowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Gąsawa', woj: 'kujawsko-pomorskie' },
{ gmina: 'Fabianki', woj: 'kujawsko-pomorskie' },
{ gmina: 'Drzycim', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dragacz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dobrzyń nad Wisłą', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dobre', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dobrcz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dębowa Łąka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dąbrowa Chełmińska', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dąbrowa Biskupia', woj: 'kujawsko-pomorskie' },
{ gmina: 'Dąbrowa', woj: 'kujawsko-pomorskie' },
{ gmina: 'Czernikowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Ciechocinek', woj: 'kujawsko-pomorskie' },
{ gmina: 'Ciechocin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Chrostkowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Chodecz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Choceń', woj: 'kujawsko-pomorskie' },
{ gmina: 'Chełmża', woj: 'kujawsko-pomorskie' },
{ gmina: 'Chełmno', woj: 'kujawsko-pomorskie' },
{ gmina: 'Cekcyn', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bytoń', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bydgoszcz', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bukowiec', woj: 'kujawsko-pomorskie' },
{ gmina: 'Brzuze', woj: 'kujawsko-pomorskie' },
{ gmina: 'Brzozie', woj: 'kujawsko-pomorskie' },
{ gmina: 'Brześć Kujawski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Brodnica', woj: 'kujawsko-pomorskie' },
{ gmina: 'Boniewo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bobrowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bobrowniki', woj: 'kujawsko-pomorskie' },
{ gmina: 'Białe Błota', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bądkowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Baruchowo', woj: 'kujawsko-pomorskie' },
{ gmina: 'Bartniczka', woj: 'kujawsko-pomorskie' },
{ gmina: 'Barcin', woj: 'kujawsko-pomorskie' },
{ gmina: 'Aleksandrów Kujawski', woj: 'kujawsko-pomorskie' },
{ gmina: 'Zalewo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Wydminy', woj: 'warmińsko-mazurskie' },
{ gmina: 'Wilczęta', woj: 'warmińsko-mazurskie' },
{ gmina: 'Wieliczki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Wielbark', woj: 'warmińsko-mazurskie' },
{ gmina: 'Węgorzewo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Tolkmicko', woj: 'warmińsko-mazurskie' },
{ gmina: 'Świątki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Szczytno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Susz', woj: 'warmińsko-mazurskie' },
{ gmina: 'Stawiguda', woj: 'warmińsko-mazurskie' },
{ gmina: 'Stare Juchy', woj: 'warmińsko-mazurskie' },
{ gmina: 'Srokowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Sorkwity', woj: 'warmińsko-mazurskie' },
{ gmina: 'Sępopol', woj: 'warmińsko-mazurskie' },
{ gmina: 'Ryn', woj: 'warmińsko-mazurskie' },
{ gmina: 'Rychliki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Rybno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Ruciane-Nida', woj: 'warmińsko-mazurskie' },
{ gmina: 'Rozogi', woj: 'warmińsko-mazurskie' },
{ gmina: 'Reszel', woj: 'warmińsko-mazurskie' },
{ gmina: 'Purda', woj: 'warmińsko-mazurskie' },
{ gmina: 'Prostki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Pozezdrze', woj: 'warmińsko-mazurskie' },
{ gmina: 'Płośnica', woj: 'warmińsko-mazurskie' },
{ gmina: 'Płoskinia', woj: 'warmińsko-mazurskie' },
{ gmina: 'Pisz', woj: 'warmińsko-mazurskie' },
{ gmina: 'Pieniężno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Piecki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Pasym', woj: 'warmińsko-mazurskie' },
{ gmina: 'Pasłęk', woj: 'warmińsko-mazurskie' },
{ gmina: 'Ostróda', woj: 'warmińsko-mazurskie' },
{ gmina: 'Orzysz', woj: 'warmińsko-mazurskie' },
{ gmina: 'Orneta', woj: 'warmińsko-mazurskie' },
{ gmina: 'Olsztynek', woj: 'warmińsko-mazurskie' },
{ gmina: 'Olsztyn', woj: 'warmińsko-mazurskie' },
{ gmina: 'Olecko', woj: 'warmińsko-mazurskie' },
{ gmina: 'Nowe Miasto Lubawskie', woj: 'warmińsko-mazurskie' },
{ gmina: 'Nidzica', woj: 'warmińsko-mazurskie' },
{ gmina: 'Mrągowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Morąg', woj: 'warmińsko-mazurskie' },
{ gmina: 'Młynary', woj: 'warmińsko-mazurskie' },
{ gmina: 'Miłomłyn', woj: 'warmińsko-mazurskie' },
{ gmina: 'Miłki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Miłakowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Milejewo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Mikołajki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Markusy', woj: 'warmińsko-mazurskie' },
{ gmina: 'Małdyty', woj: 'warmińsko-mazurskie' },
{ gmina: 'Łukta', woj: 'warmińsko-mazurskie' },
{ gmina: 'Lubomino', woj: 'warmińsko-mazurskie' },
{ gmina: 'Lubawa', woj: 'warmińsko-mazurskie' },
{ gmina: 'Lidzbark Warmiński', woj: 'warmińsko-mazurskie' },
{ gmina: 'Lidzbark', woj: 'warmińsko-mazurskie' },
{ gmina: 'Lelkowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kurzętnik', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kruklanki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kozłowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kowale Oleckie', woj: 'warmińsko-mazurskie' },
{ gmina: 'Korsze', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kolno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kiwity', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kisielice', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kętrzyn', woj: 'warmińsko-mazurskie' },
{ gmina: 'Kalinowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Jonkowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Jeziorany', woj: 'warmińsko-mazurskie' },
{ gmina: 'Jedwabno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Janowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Janowiec Kościelny', woj: 'warmińsko-mazurskie' },
{ gmina: 'Iłowo-Osada', woj: 'warmińsko-mazurskie' },
{ gmina: 'Iława', woj: 'warmińsko-mazurskie' },
{ gmina: 'Grunwald', woj: 'warmińsko-mazurskie' },
{ gmina: 'Gronowo Elbląskie', woj: 'warmińsko-mazurskie' },
{ gmina: 'Grodziczno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Górowo Iławeckie', woj: 'warmińsko-mazurskie' },
{ gmina: 'Gołdap', woj: 'warmińsko-mazurskie' },
{ gmina: 'Godkowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Giżycko', woj: 'warmińsko-mazurskie' },
{ gmina: 'Gietrzwałd', woj: 'warmińsko-mazurskie' },
{ gmina: 'Frombork', woj: 'warmińsko-mazurskie' },
{ gmina: 'Ełk', woj: 'warmińsko-mazurskie' },
{ gmina: 'Elbląg', woj: 'warmińsko-mazurskie' },
{ gmina: 'Dźwierzuty', woj: 'warmińsko-mazurskie' },
{ gmina: 'Działdowo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Dywity', woj: 'warmińsko-mazurskie' },
{ gmina: 'Dubeninki', woj: 'warmińsko-mazurskie' },
{ gmina: 'Dobre Miasto', woj: 'warmińsko-mazurskie' },
{ gmina: 'Dąbrówno', woj: 'warmińsko-mazurskie' },
{ gmina: 'Budry', woj: 'warmińsko-mazurskie' },
{ gmina: 'Braniewo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Bisztynek', woj: 'warmińsko-mazurskie' },
{ gmina: 'Biskupiec', woj: 'warmińsko-mazurskie' },
{ gmina: 'Biała Piska', woj: 'warmińsko-mazurskie' },
{ gmina: 'Bartoszyce', woj: 'warmińsko-mazurskie' },
{ gmina: 'Barczewo', woj: 'warmińsko-mazurskie' },
{ gmina: 'Barciany', woj: 'warmińsko-mazurskie' },
{ gmina: 'Banie Mazurskie', woj: 'warmińsko-mazurskie' },
{ gmina: 'Żukowice', woj: 'dolnośląskie' },
{ gmina: 'Żórawina', woj: 'dolnośląskie' },
{ gmina: 'Żmigród', woj: 'dolnośląskie' },
{ gmina: 'Żarów', woj: 'dolnośląskie' },
{ gmina: 'Złoty Stok', woj: 'dolnośląskie' },
{ gmina: 'Złotoryja', woj: 'dolnośląskie' },
{ gmina: 'Złotoryja', woj: 'dolnośląskie' },
{ gmina: 'Ziębice', woj: 'dolnośląskie' },
{ gmina: 'Zgorzelec', woj: 'dolnośląskie' },
{ gmina: 'Ząbkowice Śląskie', woj: 'dolnośląskie' },
{ gmina: 'Zawonia', woj: 'dolnośląskie' },
{ gmina: 'Zawidów', woj: 'dolnośląskie' },
{ gmina: 'Zagrodno', woj: 'dolnośląskie' },
{ gmina: 'Wrocław', woj: 'dolnośląskie' },
{ gmina: 'Wołów', woj: 'dolnośląskie' },
{ gmina: 'Wojcieszów', woj: 'dolnośląskie' },
{ gmina: 'Wleń', woj: 'dolnośląskie' },
{ gmina: 'Wisznia Mała', woj: 'dolnośląskie' },
{ gmina: 'Wińsko', woj: 'dolnośląskie' },
{ gmina: 'Wiązów', woj: 'dolnośląskie' },
{ gmina: 'Węgliniec', woj: 'dolnośląskie' },
{ gmina: 'Wąsosz', woj: 'dolnośląskie' },
{ gmina: 'Wądroże Wielkie', woj: 'dolnośląskie' },
{ gmina: 'Warta Bolesławiecka', woj: 'dolnośląskie' },
{ gmina: 'Wałbrzych', woj: 'dolnośląskie' },
{ gmina: 'Walim', woj: 'dolnośląskie' },
{ gmina: 'Udanin', woj: 'dolnośląskie' },
{ gmina: 'Twardogóra', woj: 'dolnośląskie' },
{ gmina: 'Trzebnica', woj: 'dolnośląskie' },
{ gmina: 'Święta Katarzyna', woj: 'dolnośląskie' },
{ gmina: 'Świerzawa', woj: 'dolnośląskie' },
{ gmina: 'Świeradów-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Świebodzice', woj: 'dolnośląskie' },
{ gmina: 'Świdnica', woj: 'dolnośląskie' },
{ gmina: 'Środa Śląska', woj: 'dolnośląskie' },
{ gmina: 'Ścinawa', woj: 'dolnośląskie' },
{ gmina: 'Szklarska Poręba', woj: 'dolnośląskie' },
{ gmina: 'Szczytna', woj: 'dolnośląskie' },
{ gmina: 'Szczawno-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Syców', woj: 'dolnośląskie' },
{ gmina: 'Sulików', woj: 'dolnośląskie' },
{ gmina: 'Strzelin', woj: 'dolnośląskie' },
{ gmina: 'Strzegom', woj: 'dolnośląskie' },
{ gmina: 'Stronie Śląskie', woj: 'dolnośląskie' },
{ gmina: 'Stoszowice', woj: 'dolnośląskie' },
{ gmina: 'Stare Bogaczowice', woj: 'dolnośląskie' },
{ gmina: 'Stara Kamienica', woj: 'dolnośląskie' },
{ gmina: 'Sobótka', woj: 'dolnośląskie' },
{ gmina: 'Siekierczyn', woj: 'dolnośląskie' },
{ gmina: 'Ruja', woj: 'dolnośląskie' },
{ gmina: 'Rudna', woj: 'dolnośląskie' },
{ gmina: 'Radwanice', woj: 'dolnośląskie' },
{ gmina: 'Radków', woj: 'dolnośląskie' },
{ gmina: 'Przeworno', woj: 'dolnośląskie' },
{ gmina: 'Przemków', woj: 'dolnośląskie' },
{ gmina: 'Prusice', woj: 'dolnośląskie' },
{ gmina: 'Prochowice', woj: 'dolnośląskie' },
{ gmina: 'Polkowice', woj: 'dolnośląskie' },
{ gmina: 'Polanica-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Podgórzyn', woj: 'dolnośląskie' },
{ gmina: 'Platerówka', woj: 'dolnośląskie' },
{ gmina: 'Piława Górna', woj: 'dolnośląskie' },
{ gmina: 'Pieszyce', woj: 'dolnośląskie' },
{ gmina: 'Pieńsk', woj: 'dolnośląskie' },
{ gmina: 'Pielgrzymka', woj: 'dolnośląskie' },
{ gmina: 'Piechowice', woj: 'dolnośląskie' },
{ gmina: 'Pęcław', woj: 'dolnośląskie' },
{ gmina: 'Paszowice', woj: 'dolnośląskie' },
{ gmina: 'Osiecznica', woj: 'dolnośląskie' },
{ gmina: 'Oława', woj: 'dolnośląskie' },
{ gmina: 'Olszyna', woj: 'dolnośląskie' },
{ gmina: 'Oleśnica', woj: 'dolnośląskie' },
{ gmina: 'Oborniki Śląskie', woj: 'dolnośląskie' },
{ gmina: 'Nowogrodziec', woj: 'dolnośląskie' },
{ gmina: 'Nowa Ruda', woj: 'dolnośląskie' },
{ gmina: 'Niemcza', woj: 'dolnośląskie' },
{ gmina: 'Niechlów', woj: 'dolnośląskie' },
{ gmina: 'Mysłakowice', woj: 'dolnośląskie' },
{ gmina: 'Mściwojów', woj: 'dolnośląskie' },
{ gmina: 'Mirsk', woj: 'dolnośląskie' },
{ gmina: 'Miłkowice', woj: 'dolnośląskie' },
{ gmina: 'Milicz', woj: 'dolnośląskie' },
{ gmina: 'Miękinia', woj: 'dolnośląskie' },
{ gmina: 'Międzylesie', woj: 'dolnośląskie' },
{ gmina: 'Międzybórz', woj: 'dolnośląskie' },
{ gmina: 'Mietków', woj: 'dolnośląskie' },
{ gmina: 'Marciszów', woj: 'dolnośląskie' },
{ gmina: 'Marcinowice', woj: 'dolnośląskie' },
{ gmina: 'Malczyce', woj: 'dolnośląskie' },
{ gmina: 'Łagiewniki', woj: 'dolnośląskie' },
{ gmina: 'Lwówek Śląski', woj: 'dolnośląskie' },
{ gmina: 'Lubomierz', woj: 'dolnośląskie' },
{ gmina: 'Lubawka', woj: 'dolnośląskie' },
{ gmina: 'Lubań', woj: 'dolnośląskie' },
{ gmina: 'Lewin Kłodzki', woj: 'dolnośląskie' },
{ gmina: 'Leśna', woj: 'dolnośląskie' },
{ gmina: 'Legnickie Pole', woj: 'dolnośląskie' },
{ gmina: 'Legnica', woj: 'dolnośląskie' },
{ gmina: 'Lądek-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Kunice', woj: 'dolnośląskie' },
{ gmina: 'Kudowa-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Krotoszyce', woj: 'dolnośląskie' },
{ gmina: 'Krośnice', woj: 'dolnośląskie' },
{ gmina: 'Kowary', woj: 'dolnośląskie' },
{ gmina: 'Kotla', woj: 'dolnośląskie' },
{ gmina: 'Kostomłoty', woj: 'dolnośląskie' },
{ gmina: 'Kondratowice', woj: 'dolnośląskie' },
{ gmina: 'Kobierzyce', woj: 'dolnośląskie' },
{ gmina: 'Kąty Wrocławskie', woj: 'dolnośląskie' },
{ gmina: 'Karpacz', woj: 'dolnośląskie' },
{ gmina: 'Kamienna Góra', woj: 'dolnośląskie' },
{ gmina: 'Kamieniec Ząbkowicki', woj: 'dolnośląskie' },
{ gmina: 'Jordanów Śląski', woj: 'dolnośląskie' },
{ gmina: 'Jeżów Sudecki', woj: 'dolnośląskie' },
{ gmina: 'Jerzmanowa', woj: 'dolnośląskie' },
{ gmina: 'Jemielno', woj: 'dolnośląskie' },
{ gmina: 'Jelenia Góra', woj: 'dolnośląskie' },
{ gmina: 'Jelcz-Laskowice', woj: 'dolnośląskie' },
{ gmina: 'Jedlina-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Jaworzyna Śląska', woj: 'dolnośląskie' },
{ gmina: 'Jawor', woj: 'dolnośląskie' },
{ gmina: 'Janowice Wielkie', woj: 'dolnośląskie' },
{ gmina: 'Gryfów Śląski', woj: 'dolnośląskie' },
{ gmina: 'Gromadka', woj: 'dolnośląskie' },
{ gmina: 'Grębocice', woj: 'dolnośląskie' },
{ gmina: 'Góra', woj: 'dolnośląskie' },
{ gmina: 'Głuszyca', woj: 'dolnośląskie' },
{ gmina: 'Głogów', woj: 'dolnośląskie' },
{ gmina: 'Gaworzyce', woj: 'dolnośląskie' },
{ gmina: 'Dzierżoniów', woj: 'dolnośląskie' },
{ gmina: 'Dziadowa Kłoda', woj: 'dolnośląskie' },
{ gmina: 'Duszniki-Zdrój', woj: 'dolnośląskie' },
{ gmina: 'Domaniów', woj: 'dolnośląskie' },
{ gmina: 'Dobroszyce', woj: 'dolnośląskie' },
{ gmina: 'Dobromierz', woj: 'dolnośląskie' },
{ gmina: 'Długołęka', woj: 'dolnośląskie' },
{ gmina: 'Czernica', woj: 'dolnośląskie' },
{ gmina: 'Czarny Bór', woj: 'dolnośląskie' },
{ gmina: 'Cieszków', woj: 'dolnośląskie' },
{ gmina: 'Ciepłowody', woj: 'dolnośląskie' },
{ gmina: 'Chojnów', woj: 'dolnośląskie' },
{ gmina: 'Chocianów', woj: 'dolnośląskie' },
{ gmina: 'Bystrzyca Kłodzka', woj: 'dolnośląskie' },
{ gmina: 'Brzeg Dolny', woj: 'dolnośląskie' },
{ gmina: 'Borów', woj: 'dolnośląskie' },
{ gmina: 'Bolków', woj: 'dolnośląskie' },
{ gmina: 'Bolesławiec', woj: 'dolnośląskie' },
{ gmina: 'Boguszów-Gorce', woj: 'dolnośląskie' },
{ gmina: 'Bierutów', woj: 'dolnośląskie' },
{ gmina: 'Bogatynia', woj: 'dolnośląskie' },
{ gmina: 'Bielawa', woj: 'dolnośląskie' },
{ gmina: 'Bardo', woj: 'dolnośląskie' },
{ gmina: 'Żyrzyn', woj: 'lubelskie' },
{ gmina: 'Żółkiewka', woj: 'lubelskie' },
{ gmina: 'Żmudź', woj: 'lubelskie' },
{ gmina: 'Zwierzyniec', woj: 'lubelskie' },
{ gmina: 'Zamość', woj: 'lubelskie' },
{ gmina: 'Zalesie', woj: 'lubelskie' },
{ gmina: 'Zakrzówek', woj: 'lubelskie' },
{ gmina: 'Zakrzew', woj: 'lubelskie' },
{ gmina: 'Wysokie', woj: 'lubelskie' },
{ gmina: 'Wyryki', woj: 'lubelskie' },
{ gmina: 'Wólka', woj: 'lubelskie' },
{ gmina: 'Wola Uhruska', woj: 'lubelskie' },
{ gmina: 'Wola Mysłowska', woj: 'lubelskie' },
{ gmina: 'Wojsławice', woj: 'lubelskie' },
{ gmina: 'Wojciechów', woj: 'lubelskie' },
{ gmina: 'Wojcieszków', woj: 'lubelskie' },
{ gmina: 'Wohyń', woj: 'lubelskie' },
{ gmina: 'Włodawa', woj: 'lubelskie' },
{ gmina: 'Wisznice', woj: 'lubelskie' },
{ gmina: 'Wilków', woj: 'lubelskie' },
{ gmina: 'Wilkołaz', woj: 'lubelskie' },
{ gmina: 'Wierzbica', woj: 'lubelskie' },
{ gmina: 'Werbkowice', woj: 'lubelskie' },
{ gmina: 'Wąwolnica', woj: 'lubelskie' },
{ gmina: 'Uścimów', woj: 'lubelskie' },
{ gmina: 'Urzędów', woj: 'lubelskie' },
{ gmina: 'Urszulin', woj: 'lubelskie' },
{ gmina: 'Ułęż', woj: 'lubelskie' },
{ gmina: 'Ulhówek', woj: 'lubelskie' },
{ gmina: 'Ulan-Majorat', woj: 'lubelskie' },
{ gmina: 'Uchanie', woj: 'lubelskie' },
{ gmina: 'Tyszowce', woj: 'lubelskie' },
{ gmina: 'Turobin', woj: 'lubelskie' },
{ gmina: 'Tuczna', woj: 'lubelskie' },
{ gmina: 'Trzydnik Duży', woj: 'lubelskie' },
{ gmina: 'Trzeszczany', woj: 'lubelskie' },
{ gmina: 'Trzebieszów', woj: 'lubelskie' },
{ gmina: 'Trawniki', woj: 'lubelskie' },
{ gmina: 'Tomaszów Lubelski', woj: 'lubelskie' },
{ gmina: 'Tereszpol', woj: 'lubelskie' },
{ gmina: 'Terespol', woj: 'lubelskie' },
{ gmina: 'Telatyn', woj: 'lubelskie' },
{ gmina: 'Tarnogród', woj: 'lubelskie' },
{ gmina: 'Tarnawatka', woj: 'lubelskie' },
{ gmina: 'Świdnik', woj: 'lubelskie' },
{ gmina: 'Szczebrzeszyn', woj: 'lubelskie' },
{ gmina: 'Szastarka', woj: 'lubelskie' },
{ gmina: 'Susiec', woj: 'lubelskie' },
{ gmina: 'Sułów', woj: 'lubelskie' },
{ gmina: 'Strzyżewice', woj: 'lubelskie' },
{ gmina: 'Stoczek Łukowski', woj: 'lubelskie' },
{ gmina: 'Stężyca', woj: 'lubelskie' },
{ gmina: 'Stary Zamość', woj: 'lubelskie' },
{ gmina: 'Stary Brus', woj: 'lubelskie' },
{ gmina: 'Stanin', woj: 'lubelskie' },
{ gmina: 'Spiczyn', woj: 'lubelskie' },
{ gmina: 'Sosnówka', woj: 'lubelskie' },
{ gmina: 'Sosnowica', woj: 'lubelskie' },
{ gmina: 'Sławatycze', woj: 'lubelskie' },
{ gmina: 'Skierbieszów', woj: 'lubelskie' },
{ gmina: 'Sitno', woj: 'lubelskie' },
{ gmina: 'Siennica Różana', woj: 'lubelskie' },
{ gmina: 'Siemień', woj: 'lubelskie' },
{ gmina: 'Siedliszcze', woj: 'lubelskie' },
{ gmina: 'Serokomla', woj: 'lubelskie' },
{ gmina: 'Serniki', woj: 'lubelskie' },
{ gmina: 'Sawin', woj: 'lubelskie' },
{ gmina: 'Ryki', woj: 'lubelskie' },
{ gmina: 'Rybczewice', woj: 'lubelskie' },
{ gmina: 'Rudnik', woj: 'lubelskie' },
{ gmina: 'Ruda-Huta', woj: 'lubelskie' },
{ gmina: 'Rossosz', woj: 'lubelskie' },
{ gmina: 'Rokitno', woj: 'lubelskie' },
{ gmina: 'Rejowiec Fabryczny', woj: 'lubelskie' },
{ gmina: 'Rejowiec', woj: 'lubelskie' },
{ gmina: 'Radzyń Podlaski', woj: 'lubelskie' },
{ gmina: 'Radzyń Podlaski', woj: 'lubelskie' },
{ gmina: 'Radecznica', woj: 'lubelskie' },
{ gmina: 'Rachanie', woj: 'lubelskie' },
{ gmina: 'Puławy', woj: 'lubelskie' },
{ gmina: 'Puchaczów', woj: 'lubelskie' },
{ gmina: 'Potok Wielki', woj: 'lubelskie' },
{ gmina: 'Potok Górny', woj: 'lubelskie' },
{ gmina: 'Poniatowa', woj: 'lubelskie' },
{ gmina: 'Podedwórze', woj: 'lubelskie' },
{ gmina: 'Piszczac', woj: 'lubelskie' },
{ gmina: 'Piaski', woj: 'lubelskie' },
{ gmina: 'Parczew', woj: 'lubelskie' },
{ gmina: 'Ostrówek', woj: 'lubelskie' },
{ gmina: 'Ostrów Lubelski', woj: 'lubelskie' },
{ gmina: 'Opole Lubelskie', woj: 'lubelskie' },
{ gmina: 'Obsza', woj: 'lubelskie' },
{ gmina: 'Nowodwór', woj: 'lubelskie' },
{ gmina: 'Niemce', woj: 'lubelskie' },
{ gmina: 'Nielisz', woj: 'lubelskie' },
{ gmina: 'Niedźwiada', woj: 'lubelskie' },
{ gmina: 'Niedrzwica Duża', woj: 'lubelskie' },
{ gmina: 'Nałęczów', woj: 'lubelskie' },
{ gmina: 'Modliborzyce', woj: 'lubelskie' },
{ gmina: 'Mircze', woj: 'lubelskie' },
{ gmina: 'Milejów', woj: 'lubelskie' },
{ gmina: 'Milanów', woj: 'lubelskie' },
{ gmina: 'Międzyrzec Podlaski', woj: 'lubelskie' },
{ gmina: 'Michów', woj: 'lubelskie' },
{ gmina: 'Miączyn', woj: 'lubelskie' },
{ gmina: 'Mełgiew', woj: 'lubelskie' },
{ gmina: 'Markuszów', woj: 'lubelskie' },
{ gmina: 'Łuków', woj: 'lubelskie' },
{ gmina: 'Łukowa', woj: 'lubelskie' },
{ gmina: 'Łopiennik Górny', woj: 'lubelskie' },
{ gmina: 'Łomazy', woj: 'lubelskie' },
{ gmina: 'Łęczna', woj: 'lubelskie' },
{ gmina: 'Łaziska', woj: 'lubelskie' },
{ gmina: 'Łaszczów', woj: 'lubelskie' },
{ gmina: 'Łabunie', woj: 'lubelskie' },
{ gmina: 'Ludwin', woj: 'lubelskie' },
{ gmina: 'Lubycza Królewska', woj: 'lubelskie' },
{ gmina: 'Lublin', woj: 'lubelskie' },
{ gmina: 'Lubartów', woj: 'lubelskie' },
{ gmina: 'Leśniowice', woj: 'lubelskie' },
{ gmina: 'Leśna Podlaska', woj: 'lubelskie' },
{ gmina: 'Kurów', woj: 'lubelskie' },
{ gmina: 'Księżpol', woj: 'lubelskie' },
{ gmina: 'Krzywda', woj: 'lubelskie' },
{ gmina: 'Krzczonów', woj: 'lubelskie' },
{ gmina: 'Krynice', woj: 'lubelskie' },
{ gmina: 'Kraśnik', woj: 'lubelskie' },
{ gmina: 'Kraśniczyn', woj: 'lubelskie' },
{ gmina: 'Krasnystaw', woj: 'lubelskie' },
{ gmina: 'Krasnobród', woj: 'lubelskie' },
{ gmina: 'Końskowola', woj: 'lubelskie' },
{ gmina: 'Konstantynów', woj: 'lubelskie' },
{ gmina: 'Konopnica', woj: 'lubelskie' },
{ gmina: 'Komarów-Osada', woj: 'lubelskie' },
{ gmina: 'Komarówka Podlaska', woj: 'lubelskie' },
{ gmina: 'Kodeń', woj: 'lubelskie' },
{ gmina: 'Kock', woj: 'lubelskie' },
{ gmina: 'Kłoczew', woj: 'lubelskie' },
{ gmina: 'Kąkolewnica Wschodnia', woj: 'lubelskie' },
{ gmina: 'Kazimierz Dolny', woj: 'lubelskie' },
{ gmina: 'Karczmiska', woj: 'lubelskie' },
{ gmina: 'Kamionka', woj: 'lubelskie' },
{ gmina: 'Kamień', woj: 'lubelskie' },
{ gmina: 'Józefów nad Wisłą', woj: 'lubelskie' },
{ gmina: 'Józefów', woj: 'lubelskie' },
{ gmina: 'Jeziorzany', woj: 'lubelskie' },
{ gmina: 'Jastków', woj: 'lubelskie' },
{ gmina: 'Jarczów', woj: 'lubelskie' },
{ gmina: 'Janów Podlaski', woj: 'lubelskie' },
{ gmina: 'Janów Lubelski', woj: 'lubelskie' },
{ gmina: 'Janowiec', woj: 'lubelskie' },
{ gmina: 'Jabłoń', woj: 'lubelskie' },
{ gmina: 'Jabłonna', woj: 'lubelskie' },
{ gmina: 'Izbica', woj: 'lubelskie' },
{ gmina: 'Hrubieszów', woj: 'lubelskie' },
{ gmina: 'Horodło', woj: 'lubelskie' },
{ gmina: 'Hańsk', woj: 'lubelskie' },
{ gmina: 'Hanna', woj: 'lubelskie' },
{ gmina: 'Grabowiec', woj: 'lubelskie' },
{ gmina: 'Gościeradów', woj: 'lubelskie' },
{ gmina: 'Gorzków', woj: 'lubelskie' },
{ gmina: 'Goraj', woj: 'lubelskie' },
{ gmina: 'Godziszów', woj: 'lubelskie' },
{ gmina: 'Głusk', woj: 'lubelskie' },
{ gmina: 'Garbów', woj: 'lubelskie' },
{ gmina: 'Frampol', woj: 'lubelskie' },
{ gmina: 'Firlej', woj: 'lubelskie' },
{ gmina: 'Fajsławice', woj: 'lubelskie' },
{ gmina: 'Dzwola', woj: 'lubelskie' },
{ gmina: 'Dzierzkowice', woj: 'lubelskie' },
{ gmina: 'Dubienka', woj: 'lubelskie' },
{ gmina: 'Drelów', woj: 'lubelskie' },
{ gmina: 'Dorohusk', woj: 'lubelskie' },
{ gmina: 'Dołhobyczów', woj: 'lubelskie' },
{ gmina: 'Dębowa Kłoda', woj: 'lubelskie' },
{ gmina: 'Dęblin', woj: 'lubelskie' },
{ gmina: 'Czemierniki', woj: 'lubelskie' },
{ gmina: 'Cyców', woj: 'lubelskie' },
{ gmina: 'Chrzanów', woj: 'lubelskie' },
{ gmina: 'Chodel', woj: 'lubelskie' },
{ gmina: 'Chełm', woj: 'lubelskie' },
{ gmina: 'Bychawa', woj: 'lubelskie' },
{ gmina: 'Borzechów', woj: 'lubelskie' },
{ gmina: 'Borki', woj: 'lubelskie' },
{ gmina: 'Biszcza', woj: 'lubelskie' },
{ gmina: 'Biłgoraj', woj: 'lubelskie' },
{ gmina: 'Białopole', woj: 'lubelskie' },
{ gmina: 'Biała Podlaska', woj: 'lubelskie' },
{ gmina: 'Bełżec', woj: 'lubelskie' },
{ gmina: 'Batorz', woj: 'lubelskie' },
{ gmina: 'Baranów', woj: 'lubelskie' },
{ gmina: 'Annopol', woj: 'lubelskie' },
{ gmina: 'Aleksandrów', woj: 'lubelskie' },
{ gmina: 'Adamów', woj: 'lubelskie' },
{ gmina: 'Abramów', woj: 'lubelskie' },
{ gmina: 'Złocieniec', woj: 'zachodnio-pomorskie' },
{ gmina: 'Wolin', woj: 'zachodnio-pomorskie' },
{ gmina: 'Wierzchowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Widuchowa', woj: 'zachodnio-pomorskie' },
{ gmina: 'Węgorzyno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Warnice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Wałcz', woj: 'zachodnio-pomorskie' },
{ gmina: 'Ustronie Morskie', woj: 'zachodnio-pomorskie' },
{ gmina: 'Tychowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Tuczno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Trzebiatów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Trzcińsko-Zdrój', woj: 'zachodnio-pomorskie' },
{ gmina: 'Świnoujście', woj: 'zachodnio-pomorskie' },
{ gmina: 'Świeszyno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Świerzno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Świdwin', woj: 'zachodnio-pomorskie' },
{ gmina: 'Szczecinek', woj: 'zachodnio-pomorskie' },
{ gmina: 'Szczecin', woj: 'zachodnio-pomorskie' },
{ gmina: 'Suchań', woj: 'zachodnio-pomorskie' },
{ gmina: 'Stepnica', woj: 'zachodnio-pomorskie' },
{ gmina: 'Stare Czarnowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Stara Dąbrowa', woj: 'zachodnio-pomorskie' },
{ gmina: 'Sławoborze', woj: 'zachodnio-pomorskie' },
{ gmina: 'Sławno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Siemyśl', woj: 'zachodnio-pomorskie' },
{ gmina: 'Sianów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Rymań', woj: 'zachodnio-pomorskie' },
{ gmina: 'Rewal', woj: 'zachodnio-pomorskie' },
{ gmina: 'Resko', woj: 'zachodnio-pomorskie' },
{ gmina: 'Recz', woj: 'zachodnio-pomorskie' },
{ gmina: 'Rąbino', woj: 'zachodnio-pomorskie' },
{ gmina: 'Radowo Małe', woj: 'zachodnio-pomorskie' },
{ gmina: 'Pyrzyce', woj: 'zachodnio-pomorskie' },
{ gmina: 'Przybiernów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Przelewice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Postomino', woj: 'zachodnio-pomorskie' },
{ gmina: 'Połczyn-Zdrój', woj: 'zachodnio-pomorskie' },
{ gmina: 'Police', woj: 'zachodnio-pomorskie' },
{ gmina: 'Polanów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Płoty', woj: 'zachodnio-pomorskie' },
{ gmina: 'Pełczyce', woj: 'zachodnio-pomorskie' },
{ gmina: 'Ostrowice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Osina', woj: 'zachodnio-pomorskie' },
{ gmina: 'Nowogródek Pomorski', woj: 'zachodnio-pomorskie' },
{ gmina: 'Nowogard', woj: 'zachodnio-pomorskie' },
{ gmina: 'Nowe Warpno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Myślibórz', woj: 'zachodnio-pomorskie' },
{ gmina: 'Moryń', woj: 'zachodnio-pomorskie' },
{ gmina: 'Mirosławiec', woj: 'zachodnio-pomorskie' },
{ gmina: 'Międzyzdroje', woj: 'zachodnio-pomorskie' },
{ gmina: 'Mieszkowice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Mielno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Maszewo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Marianowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Manowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Malechowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Łobez', woj: 'zachodnio-pomorskie' },
{ gmina: 'Lipiany', woj: 'zachodnio-pomorskie' },
{ gmina: 'Krzęcin', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kozielice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Koszalin', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kołobrzeg', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kołobrzeg', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kołbaskowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kobylanka', woj: 'zachodnio-pomorskie' },
{ gmina: 'Karnice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Karlino', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kamień Pomorski', woj: 'zachodnio-pomorskie' },
{ gmina: 'Kalisz Pomorski', woj: 'zachodnio-pomorskie' },
{ gmina: 'Ińsko', woj: 'zachodnio-pomorskie' },
{ gmina: 'Grzmiąca', woj: 'zachodnio-pomorskie' },
{ gmina: 'Gryfino', woj: 'zachodnio-pomorskie' },
{ gmina: 'Gryfice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Gościno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Goleniów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Golczewo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dziwnów', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dygowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Drawsko Pomorskie', woj: 'zachodnio-pomorskie' },
{ gmina: 'Drawno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dolice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dobrzany', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dobra (Szczecińska)', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dobra', woj: 'zachodnio-pomorskie' },
{ gmina: 'Dębno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Darłowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Człopa', woj: 'zachodnio-pomorskie' },
{ gmina: 'Czaplinek', woj: 'zachodnio-pomorskie' },
{ gmina: 'Choszczno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Chojna', woj: 'zachodnio-pomorskie' },
{ gmina: 'Chociwel', woj: 'zachodnio-pomorskie' },
{ gmina: 'Cedynia', woj: 'zachodnio-pomorskie' },
{ gmina: 'Brzeżno', woj: 'zachodnio-pomorskie' },
{ gmina: 'Brojce', woj: 'zachodnio-pomorskie' },
{ gmina: 'Borne Sulinowo', woj: 'zachodnio-pomorskie' },
{ gmina: 'Boleszkowice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Bobolice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Biesiekierz', woj: 'zachodnio-pomorskie' },
{ gmina: 'Bierzwnik', woj: 'zachodnio-pomorskie' },
{ gmina: 'Bielice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Biały Bór', woj: 'zachodnio-pomorskie' },
{ gmina: 'Białogard', woj: 'zachodnio-pomorskie' },
{ gmina: 'Będzino', woj: 'zachodnio-pomorskie' },
{ gmina: 'Barwice', woj: 'zachodnio-pomorskie' },
{ gmina: 'Barlinek', woj: 'zachodnio-pomorskie' },
{ gmina: 'Banie', woj: 'zachodnio-pomorskie' },
{ gmina: 'Konarzyny', woj: 'podlaskie' },
{ gmina: 'Zbójna', woj: 'podlaskie' },
{ gmina: 'Zawady', woj: 'podlaskie' },
{ gmina: 'Zambrów', woj: 'podlaskie' },
{ gmina: 'Zabłudów', woj: 'podlaskie' },
{ gmina: 'Wyszki', woj: 'podlaskie' },
{ gmina: 'Wysokie Mazowieckie', woj: 'podlaskie' },
{ gmina: 'Wiżajny', woj: 'podlaskie' },
{ gmina: 'Wizna', woj: 'podlaskie' },
{ gmina: 'Wąsosz', woj: 'podlaskie' },
{ gmina: 'Wasilków', woj: 'podlaskie' },
{ gmina: 'Tykocin', woj: 'podlaskie' },
{ gmina: 'Turośń Kościelna', woj: 'podlaskie' },
{ gmina: 'Turośl', woj: 'podlaskie' },
{ gmina: 'Trzcianne', woj: 'podlaskie' },
{ gmina: 'Śniadowo', woj: 'podlaskie' },
{ gmina: 'Szypliszki', woj: 'podlaskie' },
{ gmina: 'Szumowo', woj: 'podlaskie' },
{ gmina: 'Szudziałowo', woj: 'podlaskie' },
{ gmina: 'Sztabin', woj: 'podlaskie' },
{ gmina: 'Szepietowo', woj: 'podlaskie' },
{ gmina: 'Szczuczyn', woj: 'podlaskie' },
{ gmina: 'Suwałki', woj: 'podlaskie' },
{ gmina: 'Suraż', woj: 'podlaskie' },
{ gmina: 'Supraśl', woj: 'podlaskie' },
{ gmina: 'Suchowola', woj: 'podlaskie' },
{ gmina: 'Stawiski', woj: 'podlaskie' },
{ gmina: 'Sokółka', woj: 'podlaskie' },
{ gmina: 'Sokoły', woj: 'podlaskie' },
{ gmina: 'Siemiatycze', woj: 'podlaskie' },
{ gmina: 'Sidra', woj: 'podlaskie' },
{ gmina: 'Sejny', woj: 'podlaskie' },
{ gmina: 'Sejny', woj: 'podlaskie' },
{ gmina: 'Rutki', woj: 'podlaskie' },
{ gmina: 'Rutka-Tartak', woj: 'podlaskie' },
{ gmina: 'Rudka', woj: 'podlaskie' },
{ gmina: 'Rajgród', woj: 'podlaskie' },
{ gmina: 'Radziłów', woj: 'podlaskie' },
{ gmina: 'Raczki', woj: 'podlaskie' },
{ gmina: 'Puńsk', woj: 'podlaskie' },
{ gmina: 'Przytuły', woj: 'podlaskie' },
{ gmina: 'Przerośl', woj: 'podlaskie' },
{ gmina: 'Poświętne', woj: 'podlaskie' },
{ gmina: 'Płaska', woj: 'podlaskie' },
{ gmina: 'Piątnica', woj: 'podlaskie' },
{ gmina: 'Perlejewo', woj: 'podlaskie' },
{ gmina: 'Orla', woj: 'podlaskie' },
{ gmina: 'Nurzec-Stacja', woj: 'podlaskie' },
{ gmina: 'Nowy Dwór', woj: 'podlaskie' },
{ gmina: 'Nowogród', woj: 'podlaskie' },
{ gmina: 'Nowinka', woj: 'podlaskie' },
{ gmina: 'Nowe Piekuty', woj: 'podlaskie' },
{ gmina: 'Narewka', woj: 'podlaskie' },
{ gmina: 'Narew', woj: 'podlaskie' },
{ gmina: 'Mońki', woj: 'podlaskie' },
{ gmina: 'Milejczyce', woj: 'podlaskie' },
{ gmina: 'Mielnik', woj: 'podlaskie' },
{ gmina: 'Michałowo', woj: 'podlaskie' },
{ gmina: 'Miastkowo', woj: 'podlaskie' },
{ gmina: 'Mały Płock', woj: 'podlaskie' },
{ gmina: 'Łomża', woj: 'podlaskie' },
{ gmina: 'Łapy', woj: 'podlaskie' },
{ gmina: 'Lipsk', woj: 'podlaskie' },
{ gmina: 'Kuźnica', woj: 'podlaskie' },
{ gmina: 'Kulesze Kościelne', woj: 'podlaskie' },
{ gmina: 'Krypno', woj: 'podlaskie' },
{ gmina: 'Krynki', woj: 'podlaskie' },
{ gmina: 'Krasnopol', woj: 'podlaskie' },
{ gmina: 'Korycin', woj: 'podlaskie' },
{ gmina: 'Kołaki Kościelne', woj: 'podlaskie' },
{ gmina: 'Kolno', woj: 'podlaskie' },
{ gmina: 'Kobylin-Borzymy', woj: 'podlaskie' },
{ gmina: 'Knyszyn', woj: 'podlaskie' },
{ gmina: 'Klukowo', woj: 'podlaskie' },
{ gmina: 'Kleszczele', woj: 'podlaskie' },
{ gmina: 'Juchnowiec Kościelny', woj: 'podlaskie' },
{ gmina: 'Jeleniewo', woj: 'podlaskie' },
{ gmina: 'Jedwabne', woj: 'podlaskie' },
{ gmina: 'Jaświły', woj: 'podlaskie' },
{ gmina: 'Jasionówka', woj: 'podlaskie' },
{ gmina: 'Janów', woj: 'podlaskie' },
{ gmina: 'Hajnówka', woj: 'podlaskie' },
{ gmina: 'Gródek', woj: 'podlaskie' },
{ gmina: 'Grodzisk', woj: 'podlaskie' },
{ gmina: 'Grajewo', woj: 'podlaskie' },
{ gmina: 'Grabowo', woj: 'podlaskie' },
{ gmina: 'Goniądz', woj: 'podlaskie' },
{ gmina: 'Giby', woj: 'podlaskie' },
{ gmina: 'Filipów', woj: 'podlaskie' },
{ gmina: 'Dziadkowice', woj: 'podlaskie' },
{ gmina: 'Dubicze Cerkiewne', woj: 'podlaskie' },
{ gmina: 'Drohiczyn', woj: 'podlaskie' },
{ gmina: 'Dobrzyniewo Duże', woj: 'podlaskie' },
{ gmina: 'Dąbrowa Białostocka', woj: 'podlaskie' },
{ gmina: 'Czyżew-Osada', woj: 'podlaskie' },
{ gmina: 'Czyże', woj: 'podlaskie' },
{ gmina: 'Czeremcha', woj: 'podlaskie' },
{ gmina: 'Czarna Białostocka', woj: 'podlaskie' },
{ gmina: 'Ciechanowiec', woj: 'podlaskie' },
{ gmina: 'Choroszcz', woj: 'podlaskie' },
{ gmina: 'Brańsk', woj: 'podlaskie' },
{ gmina: 'Brańsk', woj: 'podlaskie' },
{ gmina: 'Boćki', woj: 'podlaskie' },
{ gmina: 'Bielsk Podlaski', woj: 'podlaskie' },
{ gmina: 'Białystok', woj: 'podlaskie' },
{ gmina: 'Białowieża', woj: 'podlaskie' },
{ gmina: 'Bargłów Kościelny', woj: 'podlaskie' },
{ gmina: 'Bakałarzewo', woj: 'podlaskie' },
{ gmina: 'Augustów', woj: 'podlaskie' },
{ gmina: 'Żary', woj: 'lubuskie' },
{ gmina: 'Żagań', woj: 'lubuskie' },
{ gmina: 'Zwierzyn', woj: 'lubuskie' },
{ gmina: 'Zielona Góra', woj: 'lubuskie' },
{ gmina: 'Zbąszynek', woj: 'lubuskie' },
{ gmina: 'Zabór', woj: 'lubuskie' },
{ gmina: 'Wymiarki', woj: 'lubuskie' },
{ gmina: 'Wschowa', woj: 'lubuskie' },
{ gmina: 'Witnica', woj: 'lubuskie' },
{ gmina: 'Tuplice', woj: 'lubuskie' },
{ gmina: 'Trzebiel', woj: 'lubuskie' },
{ gmina: 'Trzebiechów', woj: 'lubuskie' },
{ gmina: 'Trzciel', woj: 'lubuskie' },
{ gmina: 'Torzym', woj: 'lubuskie' },
{ gmina: 'Torzym', woj: 'lubuskie' },
{ gmina: 'Świebodzin', woj: 'lubuskie' },
{ gmina: 'Świdnica', woj: 'lubuskie' },
{ gmina: 'Szprotawa', woj: 'lubuskie' },
{ gmina: 'Szlichtyngowa', woj: 'lubuskie' },
{ gmina: 'Szczaniec', woj: 'lubuskie' },
{ gmina: 'Sulęcin', woj: 'lubuskie' },
{ gmina: 'Sulechów', woj: 'lubuskie' },
{ gmina: 'Strzelce Krajeńskie', woj: 'lubuskie' },
{ gmina: 'Stare Kurowo', woj: 'lubuskie' },
{ gmina: 'Słubice', woj: 'lubuskie' },
{ gmina: 'Słońsk', woj: 'lubuskie' },
{ gmina: 'Sława', woj: 'lubuskie' },
{ gmina: 'Skwierzyna', woj: 'lubuskie' },
{ gmina: 'Skąpe', woj: 'lubuskie' },
{ gmina: 'Siedlisko', woj: 'lubuskie' },
{ gmina: 'Santok', woj: 'lubuskie' },
{ gmina: 'Rzepin', woj: 'lubuskie' },
{ gmina: 'Pszczew', woj: 'lubuskie' },
{ gmina: 'Przytoczna', woj: 'lubuskie' },
{ gmina: 'Przewóz', woj: 'lubuskie' },
{ gmina: 'Otyń', woj: 'lubuskie' },
{ gmina: 'Ośno Lubuskie', woj: 'lubuskie' },
{ gmina: 'Nowogród Bobrzański', woj: 'lubuskie' },
{ gmina: 'Nowe Miasteczko', woj: 'lubuskie' },
{ gmina: 'Nowa Sól', woj: 'lubuskie' },
{ gmina: 'Niegosławice', woj: 'lubuskie' },
{ gmina: 'Międzyrzecz', woj: 'lubuskie' },
{ gmina: 'Maszewo', woj: 'lubuskie' },
{ gmina: 'Małomice', woj: 'lubuskie' },
{ gmina: 'Łęknica', woj: 'lubuskie' },
{ gmina: 'Łagów', woj: 'lubuskie' },
{ gmina: 'Lubsko', woj: 'lubuskie' },
{ gmina: 'Lubrza', woj: 'lubuskie' },
{ gmina: 'Lubniewice', woj: 'lubuskie' },
{ gmina: 'Lubiszyn', woj: 'lubuskie' },
{ gmina: 'Lipinki Łużyckie', woj: 'lubuskie' },
{ gmina: 'Krzeszyce', woj: 'lubuskie' },
{ gmina: 'Krosno Odrzańskie', woj: 'lubuskie' },
{ gmina: 'Kożuchów', woj: 'lubuskie' },
{ gmina: 'Kostrzyn nad Odrą', woj: 'lubuskie' },
{ gmina: 'Kolsko', woj: 'lubuskie' },
{ gmina: 'Kłodawa', woj: 'lubuskie' },
{ gmina: 'Kargowa', woj: 'lubuskie' },
{ gmina: 'Jasień', woj: 'lubuskie' },
{ gmina: 'Iłowa', woj: 'lubuskie' },
{ gmina: 'Gubin', woj: 'lubuskie' },
{ gmina: 'Górzyca', woj: 'lubuskie' },
{ gmina: 'Gozdnica', woj: 'lubuskie' },
{ gmina: 'Gorzów Wielkopolski', woj: 'lubuskie' },
{ gmina: 'Drezdenko', woj: 'lubuskie' },
{ gmina: 'Dobiegniew', woj: 'lubuskie' },
{ gmina: 'Deszczno', woj: 'lubuskie' },
{ gmina: 'Dąbie', woj: 'lubuskie' },
{ gmina: 'Czerwieńsk', woj: 'lubuskie' },
{ gmina: 'Cybinka', woj: 'lubuskie' },
{ gmina: 'Bytom Odrzański', woj: 'lubuskie' },
{ gmina: 'Bytnica', woj: 'lubuskie' },
{ gmina: 'Brzeźnica', woj: 'lubuskie' },
{ gmina: 'Brody', woj: 'lubuskie' },
{ gmina: 'Bojadła', woj: 'lubuskie' },
{ gmina: 'Bogdaniec', woj: 'lubuskie' },
{ gmina: 'Bobrowice', woj: 'lubuskie' },
{ gmina: 'Bledzew', woj: 'lubuskie' },
{ gmina: 'Babimost', woj: 'lubuskie' },
{ gmina: 'Żerków', woj: 'wielkopolskie' },
{ gmina: 'Żelazków', woj: 'wielkopolskie' },
{ gmina: 'Złotów', woj: 'wielkopolskie' },
{ gmina: 'Zduny', woj: 'wielkopolskie' },
{ gmina: 'Zbąszyń', woj: 'wielkopolskie' },
{ gmina: 'Zaniemyśl', woj: 'wielkopolskie' },
{ gmina: 'Zakrzewo', woj: 'wielkopolskie' },
{ gmina: 'Zagórów', woj: 'wielkopolskie' },
{ gmina: 'Wysoka', woj: 'wielkopolskie' },
{ gmina: 'Wyrzysk', woj: 'wielkopolskie' },
{ gmina: 'Września', woj: 'wielkopolskie' },
{ gmina: 'Wronki', woj: 'wielkopolskie' },
{ gmina: 'Wolsztyn', woj: 'wielkopolskie' },
{ gmina: 'Włoszakowice', woj: 'wielkopolskie' },
{ gmina: 'Władysławów', woj: 'wielkopolskie' },
{ gmina: 'Witkowo', woj: 'wielkopolskie' },
{ gmina: 'Wilczyn', woj: 'wielkopolskie' },
{ gmina: 'Wijewo', woj: 'wielkopolskie' },
{ gmina: 'Wierzbinek', woj: 'wielkopolskie' },
{ gmina: 'Wielichowo', woj: 'wielkopolskie' },
{ gmina: 'Wieleń', woj: 'wielkopolskie' },
{ gmina: 'Wągrowiec', woj: 'wielkopolskie' },
{ gmina: 'Wapno', woj: 'wielkopolskie' },
{ gmina: 'Ujście', woj: 'wielkopolskie' },
{ gmina: 'Turek', woj: 'wielkopolskie' },
{ gmina: 'Tuliszków', woj: 'wielkopolskie' },
{ gmina: 'Trzemeszno', woj: 'wielkopolskie' },
{ gmina: 'Trzcinica', woj: 'wielkopolskie' },
{ gmina: 'Trzcianka', woj: 'wielkopolskie' },
{ gmina: 'Tarnówka', woj: 'wielkopolskie' },
{ gmina: 'Tarnowo Podgórne', woj: 'wielkopolskie' },
{ gmina: 'Święciechowa', woj: 'wielkopolskie' },
{ gmina: 'Środa Wielkopolska', woj: 'wielkopolskie' },
{ gmina: 'Śrem', woj: 'wielkopolskie' },
{ gmina: 'Śmigiel', woj: 'wielkopolskie' },
{ gmina: 'Ślesin', woj: 'wielkopolskie' },
{ gmina: 'Szydłowo', woj: 'wielkopolskie' },
{ gmina: 'Szczytniki', woj: 'wielkopolskie' },
{ gmina: 'Szamotuły', woj: 'wielkopolskie' },
{ gmina: 'Szamocin', woj: 'wielkopolskie' },
{ gmina: 'Swarzędz', woj: 'wielkopolskie' },
{ gmina: 'Sulmierzyce', woj: 'wielkopolskie' },
{ gmina: 'Suchy Las', woj: 'wielkopolskie' },
{ gmina: 'Strzałkowo', woj: 'wielkopolskie' },
{ gmina: 'Stęszew', woj: 'wielkopolskie' },
{ gmina: 'Stawiszyn', woj: 'wielkopolskie' },
{ gmina: 'Stare Miasto', woj: 'wielkopolskie' },
{ gmina: 'Sośnie', woj: 'wielkopolskie' },
{ gmina: 'Sompolno', woj: 'wielkopolskie' },
{ gmina: 'Słupca', woj: 'wielkopolskie' },
{ gmina: 'Skulsk', woj: 'wielkopolskie' },
{ gmina: 'Skoki', woj: 'wielkopolskie' },
{ gmina: 'Sieroszewice', woj: 'wielkopolskie' },
{ gmina: 'Sieraków', woj: 'wielkopolskie' },
{ gmina: 'Siedlec', woj: 'wielkopolskie' },
{ gmina: 'Rzgów', woj: 'wielkopolskie' },
{ gmina: 'Rydzyna', woj: 'wielkopolskie' },
{ gmina: 'Ryczywół', woj: 'wielkopolskie' },
{ gmina: 'Rychwał', woj: 'wielkopolskie' },
{ gmina: 'Rychtal', woj: 'wielkopolskie' },
{ gmina: 'Rozdrażew', woj: 'wielkopolskie' },
{ gmina: 'Rokietnica', woj: 'wielkopolskie' },
{ gmina: 'Rogoźno', woj: 'wielkopolskie' },
{ gmina: 'Rawicz', woj: 'wielkopolskie' },
{ gmina: 'Raszków', woj: 'wielkopolskie' },
{ gmina: 'Rakoniewice', woj: 'wielkopolskie' },
{ gmina: 'Pyzdry', woj: 'wielkopolskie' },
{ gmina: 'Puszczykowo', woj: 'wielkopolskie' },
{ gmina: 'Przykona', woj: 'wielkopolskie' },
{ gmina: 'Przygodzice', woj: 'wielkopolskie' },
{ gmina: 'Przemęt', woj: 'wielkopolskie' },
{ gmina: 'Przedecz', woj: 'wielkopolskie' },
{ gmina: 'Poznań', woj: 'wielkopolskie' },
{ gmina: 'Powidz', woj: 'wielkopolskie' },
{ gmina: 'Poniec', woj: 'wielkopolskie' },
{ gmina: 'Połajewo', woj: 'wielkopolskie' },
{ gmina: 'Pogorzela', woj: 'wielkopolskie' },
{ gmina: 'Pobiedziska', woj: 'wielkopolskie' },
{ gmina: 'Pniewy', woj: 'wielkopolskie' },
{ gmina: 'Pleszew', woj: 'wielkopolskie' },
{ gmina: 'Piła', woj: 'wielkopolskie' },
{ gmina: 'Piaski', woj: 'wielkopolskie' },
{ gmina: 'Pępowo', woj: 'wielkopolskie' },
{ gmina: 'Perzów', woj: 'wielkopolskie' },
{ gmina: 'Pakosław', woj: 'wielkopolskie' },
{ gmina: 'Ostrzeszów', woj: 'wielkopolskie' },
{ gmina: 'Ostrów Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Ostrowite', woj: 'wielkopolskie' },
{ gmina: 'Ostroróg', woj: 'wielkopolskie' },
{ gmina: 'Osiek Mały', woj: 'wielkopolskie' },
{ gmina: 'Osieczna', woj: 'wielkopolskie' },
{ gmina: 'Orchowo', woj: 'wielkopolskie' },
{ gmina: 'Opatówek', woj: 'wielkopolskie' },
{ gmina: 'Opalenica', woj: 'wielkopolskie' },
{ gmina: 'Olszówka', woj: 'wielkopolskie' },
{ gmina: 'Okonek', woj: 'wielkopolskie' },
{ gmina: 'Odolanów', woj: 'wielkopolskie' },
{ gmina: 'Obrzycko', woj: 'wielkopolskie' },
{ gmina: 'Oborniki', woj: 'wielkopolskie' },
{ gmina: 'Nowy Tomyśl', woj: 'wielkopolskie' },
{ gmina: 'Nowe Skalmierzyce', woj: 'wielkopolskie' },
{ gmina: 'Nowe Miasto nad Wartą', woj: 'wielkopolskie' },
{ gmina: 'Niechanowo', woj: 'wielkopolskie' },
{ gmina: 'Nekla', woj: 'wielkopolskie' },
{ gmina: 'Mycielin', woj: 'wielkopolskie' },
{ gmina: 'Murowana Goślina', woj: 'wielkopolskie' },
{ gmina: 'Mosina', woj: 'wielkopolskie' },
{ gmina: 'Miłosław', woj: 'wielkopolskie' },
{ gmina: 'Mikstat', woj: 'wielkopolskie' },
{ gmina: 'Międzychód', woj: 'wielkopolskie' },
{ gmina: 'Mieścisko', woj: 'wielkopolskie' },
{ gmina: 'Mieleszyn', woj: 'wielkopolskie' },
{ gmina: 'Mieleszyn', woj: 'wielkopolskie' },
{ gmina: 'Miejska Górka', woj: 'wielkopolskie' },
{ gmina: 'Miedzichowo', woj: 'wielkopolskie' },
{ gmina: 'Miasteczko Krajeńskie', woj: 'wielkopolskie' },
{ gmina: 'Margonin', woj: 'wielkopolskie' },
{ gmina: 'Malanów', woj: 'wielkopolskie' },
{ gmina: 'Łubowo', woj: 'wielkopolskie' },
{ gmina: 'Łobżenica', woj: 'wielkopolskie' },
{ gmina: 'Łęka Opatowska', woj: 'wielkopolskie' },
{ gmina: 'Lwówek', woj: 'wielkopolskie' },
{ gmina: 'Luboń', woj: 'wielkopolskie' },
{ gmina: 'Lubasz', woj: 'wielkopolskie' },
{ gmina: 'Lisków', woj: 'wielkopolskie' },
{ gmina: 'Lipno', woj: 'wielkopolskie' },
{ gmina: 'Lipka', woj: 'wielkopolskie' },
{ gmina: 'Leszno', woj: 'wielkopolskie' },
{ gmina: 'Lądek', woj: 'wielkopolskie' },
{ gmina: 'Kwilcz', woj: 'wielkopolskie' },
{ gmina: 'Kuślin', woj: 'wielkopolskie' },
{ gmina: 'Książ Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Krzyż Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Krzywiń', woj: 'wielkopolskie' },
{ gmina: 'Krzymów', woj: 'wielkopolskie' },
{ gmina: 'Krzykosy', woj: 'wielkopolskie' },
{ gmina: 'Krzemieniewo', woj: 'wielkopolskie' },
{ gmina: 'Krotoszyn', woj: 'wielkopolskie' },
{ gmina: 'Krobia', woj: 'wielkopolskie' },
{ gmina: 'Kraszewice', woj: 'wielkopolskie' },
{ gmina: 'Kramsk', woj: 'wielkopolskie' },
{ gmina: 'Krajenka', woj: 'wielkopolskie' },
{ gmina: 'Kórnik', woj: 'wielkopolskie' },
{ gmina: 'Koźminek', woj: 'wielkopolskie' },
{ gmina: 'Koźmin Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Kotlin', woj: 'wielkopolskie' },
{ gmina: 'Kościelec', woj: 'wielkopolskie' },
{ gmina: 'Kościan', woj: 'wielkopolskie' },
{ gmina: 'Kostrzyn', woj: 'wielkopolskie' },
{ gmina: 'Konin', woj: 'wielkopolskie' },
{ gmina: 'Komorniki', woj: 'wielkopolskie' },
{ gmina: 'Koło', woj: 'wielkopolskie' },
{ gmina: 'Koło', woj: 'wielkopolskie' },
{ gmina: 'Kołaczkowo', woj: 'wielkopolskie' },
{ gmina: 'Kobylin', woj: 'wielkopolskie' },
{ gmina: 'Kobyla Góra', woj: 'wielkopolskie' },
{ gmina: 'Kłodawa', woj: 'wielkopolskie' },
{ gmina: 'Kłecko', woj: 'wielkopolskie' },
{ gmina: 'Kleszczewo', woj: 'wielkopolskie' },
{ gmina: 'Kleczew', woj: 'wielkopolskie' },
{ gmina: 'Kiszkowo', woj: 'wielkopolskie' },
{ gmina: 'Kępno', woj: 'wielkopolskie' },
{ gmina: 'Kaźmierz', woj: 'wielkopolskie' },
{ gmina: 'Kazimierz Biskupi', woj: 'wielkopolskie' },
{ gmina: 'Kawęczyn', woj: 'wielkopolskie' },
{ gmina: 'Kamieniec', woj: 'wielkopolskie' },
{ gmina: 'Kalisz', woj: 'wielkopolskie' },
{ gmina: 'Kaczory', woj: 'wielkopolskie' },
{ gmina: 'Jutrosin', woj: 'wielkopolskie' },
{ gmina: 'Jastrowie', woj: 'wielkopolskie' },
{ gmina: 'Jarocin', woj: 'wielkopolskie' },
{ gmina: 'Jaraczewo', woj: 'wielkopolskie' },
{ gmina: 'Grzegorzew', woj: 'wielkopolskie' },
{ gmina: 'Grodzisk Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Grodziec', woj: 'wielkopolskie' },
{ gmina: 'Granowo', woj: 'wielkopolskie' },
{ gmina: 'Grabów nad Prosną', woj: 'wielkopolskie' },
{ gmina: 'Gostyń', woj: 'wielkopolskie' },
{ gmina: 'Gołuchów', woj: 'wielkopolskie' },
{ gmina: 'Gołańcz', woj: 'wielkopolskie' },
{ gmina: 'Golina', woj: 'wielkopolskie' },
{ gmina: 'Godziesze Wielkie', woj: 'wielkopolskie' },
{ gmina: 'Gizałki', woj: 'wielkopolskie' },
{ gmina: 'Duszniki', woj: 'wielkopolskie' },
{ gmina: 'Drawsko', woj: 'wielkopolskie' },
{ gmina: 'Doruchów', woj: 'wielkopolskie' },
{ gmina: 'Dopiewo', woj: 'wielkopolskie' },
{ gmina: 'Dominowo', woj: 'wielkopolskie' },
{ gmina: 'Dolsk', woj: 'wielkopolskie' },
{ gmina: 'Dobrzyca', woj: 'wielkopolskie' },
{ gmina: 'Dobra', woj: 'wielkopolskie' },
{ gmina: 'Dąbie', woj: 'wielkopolskie' },
{ gmina: 'Damasławek', woj: 'wielkopolskie' },
{ gmina: 'Czerwonak', woj: 'wielkopolskie' },
{ gmina: 'Czerniejewo', woj: 'wielkopolskie' },
{ gmina: 'Czempiń', woj: 'wielkopolskie' },
{ gmina: 'Czarnków', woj: 'wielkopolskie' },
{ gmina: 'Czajków', woj: 'wielkopolskie' },
{ gmina: 'Chrzypsko Wielkie', woj: 'wielkopolskie' },
{ gmina: 'Chodzież', woj: 'wielkopolskie' },
{ gmina: 'Chodów', woj: 'wielkopolskie' },
{ gmina: 'Chocz', woj: 'wielkopolskie' },
{ gmina: 'Ceków-Kolonia', woj: 'wielkopolskie' },
{ gmina: 'Buk', woj: 'wielkopolskie' },
{ gmina: 'Budzyń', woj: 'wielkopolskie' },
{ gmina: 'Brzeziny', woj: 'wielkopolskie' },
{ gmina: 'Brudzew', woj: 'wielkopolskie' },
{ gmina: 'Brodnica', woj: 'wielkopolskie' },
{ gmina: 'Bralin', woj: 'wielkopolskie' },
{ gmina: 'Borek Wielkopolski', woj: 'wielkopolskie' },
{ gmina: 'Bojanowo', woj: 'wielkopolskie' },
{ gmina: 'Blizanów', woj: 'wielkopolskie' },
{ gmina: 'Białośliwie', woj: 'wielkopolskie' },
{ gmina: 'Baranów', woj: 'wielkopolskie' },
{ gmina: 'Babiak', woj: 'wielkopolskie' },
{ gmina: 'Żyrardów', woj: 'mazowieckie' },
{ gmina: 'Żuromin', woj: 'mazowieckie' },
{ gmina: 'Żelechów', woj: 'mazowieckie' },
{ gmina: 'Żabia Wola', woj: 'mazowieckie' },
{ gmina: 'Zwoleń', woj: 'mazowieckie' },
{ gmina: 'Zielonka', woj: 'mazowieckie' },
{ gmina: 'Zbuczyn', woj: 'mazowieckie' },
{ gmina: 'Ząbki', woj: 'mazowieckie' },
{ gmina: 'Zawidz', woj: 'mazowieckie' },
{ gmina: 'Zatory', woj: 'mazowieckie' },
{ gmina: 'Zaręby Kościelne', woj: 'mazowieckie' },
{ gmina: 'Załuski', woj: 'mazowieckie' },
{ gmina: 'Zakrzew', woj: 'mazowieckie' },
{ gmina: 'Zakroczym', woj: 'mazowieckie' },
{ gmina: 'Zabrodzie', woj: 'mazowieckie' },
{ gmina: 'Wyśmierzyce', woj: 'mazowieckie' },
{ gmina: 'Wyszogród', woj: 'mazowieckie' },
{ gmina: 'Wyszków', woj: 'mazowieckie' },
{ gmina: 'Wołomin', woj: 'mazowieckie' },
{ gmina: 'Wolanów', woj: 'mazowieckie' },
{ gmina: 'Wodynie', woj: 'mazowieckie' },
{ gmina: 'Wiśniewo', woj: 'mazowieckie' },
{ gmina: 'Wiśniew', woj: 'mazowieckie' },
{ gmina: 'Wiskitki', woj: 'mazowieckie' },
{ gmina: 'Winnica', woj: 'mazowieckie' },
{ gmina: 'Wilga', woj: 'mazowieckie' },
{ gmina: 'Wierzbno', woj: 'mazowieckie' },
{ gmina: 'Wierzbno', woj: 'mazowieckie' },
{ gmina: 'Wierzbica', woj: 'mazowieckie' },
{ gmina: 'Wieniawa', woj: 'mazowieckie' },
{ gmina: 'Wieliszew', woj: 'mazowieckie' },
{ gmina: 'Wieczfnia Kościelna', woj: 'mazowieckie' },
{ gmina: 'Wiązowna', woj: 'mazowieckie' },
{ gmina: 'Węgrów', woj: 'mazowieckie' },
{ gmina: 'Wąsewo', woj: 'mazowieckie' },
{ gmina: 'Warszawa', woj: 'mazowieckie' },
{ gmina: 'Warka', woj: 'mazowieckie' },
{ gmina: 'Troszyn', woj: 'mazowieckie' },
{ gmina: 'Trojanów', woj: 'mazowieckie' },
{ gmina: 'Tłuszcz', woj: 'mazowieckie' },
{ gmina: 'Teresin', woj: 'mazowieckie' },
{ gmina: 'Tczów', woj: 'mazowieckie' },
{ gmina: 'Tarczyn', woj: 'mazowieckie' },
{ gmina: 'Świercze', woj: 'mazowieckie' },
{ gmina: 'Szydłowo', woj: 'mazowieckie' },
{ gmina: 'Szydłowiec', woj: 'mazowieckie' },
{ gmina: 'Szulborze Wielkie', woj: 'mazowieckie' },
{ gmina: 'Szreńsk', woj: 'mazowieckie' },
{ gmina: 'Szelków', woj: 'mazowieckie' },
{ gmina: 'Szczutowo', woj: 'mazowieckie' },
{ gmina: 'Szczawin Kościelny', woj: 'mazowieckie' },
{ gmina: 'Sypniewo', woj: 'mazowieckie' },
{ gmina: 'Sulejówek', woj: 'mazowieckie' },
{ gmina: 'Suchożebry', woj: 'mazowieckie' },
{ gmina: 'Stupsk', woj: 'mazowieckie' },
{ gmina: 'Strzegowo', woj: 'mazowieckie' },
{ gmina: 'Stromiec', woj: 'mazowieckie' },
{ gmina: 'Strachówka', woj: 'mazowieckie' },
{ gmina: 'Stoczek', woj: 'mazowieckie' },
{ gmina: 'Sterdyń', woj: 'mazowieckie' },
{ gmina: 'Stary Lubotyń', woj: 'mazowieckie' },
{ gmina: 'Staroźreby', woj: 'mazowieckie' },
{ gmina: 'Stare Babice', woj: 'mazowieckie' },
{ gmina: 'Stara Kornica', woj: 'mazowieckie' },
{ gmina: 'Stara Błotnica', woj: 'mazowieckie' },
{ gmina: 'Stara Biała', woj: 'mazowieckie' },
{ gmina: 'Stanisławów', woj: 'mazowieckie' },
{ gmina: 'Sońsk', woj: 'mazowieckie' },
{ gmina: 'Somianka', woj: 'mazowieckie' },
{ gmina: 'Solec nad Wisłą', woj: 'mazowieckie' },
{ gmina: 'Sokołów Podlaski', woj: 'mazowieckie' },
{ gmina: 'Sochocin', woj: 'mazowieckie' },
{ gmina: 'Sochaczew', woj: 'mazowieckie' },
{ gmina: 'Sobolew', woj: 'mazowieckie' },
{ gmina: 'Sobienie-Jeziory', woj: 'mazowieckie' },
{ gmina: 'Słupno', woj: 'mazowieckie' },
{ gmina: 'Słubice', woj: 'mazowieckie' },
{ gmina: 'Skórzec', woj: 'mazowieckie' },
{ gmina: 'Skaryszew', woj: 'mazowieckie' },
{ gmina: 'Sierpc', woj: 'mazowieckie' },
{ gmina: 'Sienno', woj: 'mazowieckie' },
{ gmina: 'Siennica', woj: 'mazowieckie' },
{ gmina: 'Siemiątkowo', woj: 'mazowieckie' },
{ gmina: 'Siedlce', woj: 'mazowieckie' },
{ gmina: 'Sieciechów', woj: 'mazowieckie' },
{ gmina: 'Serock', woj: 'mazowieckie' },
{ gmina: 'Sarnaki', woj: 'mazowieckie' },
{ gmina: 'Sanniki', woj: 'mazowieckie' },
{ gmina: 'Sadowne', woj: 'mazowieckie' },
{ gmina: 'Sabnie', woj: 'mazowieckie' },
{ gmina: 'Rzewnie', woj: 'mazowieckie' },
{ gmina: 'Rzekuń', woj: 'mazowieckie' },
{ gmina: 'Rzeczniów', woj: 'mazowieckie' },
{ gmina: 'Rząśnik', woj: 'mazowieckie' },
{ gmina: 'Rybno', woj: 'mazowieckie' },
{ gmina: 'Rusinów', woj: 'mazowieckie' },
{ gmina: 'Różan', woj: 'mazowieckie' },
{ gmina: 'Rościszewo', woj: 'mazowieckie' },
{ gmina: 'Repki', woj: 'mazowieckie' },
{ gmina: 'Regimin', woj: 'mazowieckie' },
{ gmina: 'Raszyn', woj: 'mazowieckie' },
{ gmina: 'Radzymin', woj: 'mazowieckie' },
{ gmina: 'Radziejowice', woj: 'mazowieckie' },
{ gmina: 'Radzanów - powiat białobrzeski', woj: 'mazowieckie' },
{ gmina: 'Radzanów - powiat mławski', woj: 'mazowieckie' },
{ gmina: 'Radzanowo', woj: 'mazowieckie' },
{ gmina: 'Radom', woj: 'mazowieckie' },
{ gmina: 'Raciąż', woj: 'mazowieckie' },
{ gmina: 'Puszcza Mariańska', woj: 'mazowieckie' },
{ gmina: 'Pułtusk', woj: 'mazowieckie' },
{ gmina: 'Przytyk', woj: 'mazowieckie' },
{ gmina: 'Przysucha', woj: 'mazowieckie' },
{ gmina: 'Przyłęk', woj: 'mazowieckie' },
{ gmina: 'Przesmyki', woj: 'mazowieckie' },
{ gmina: 'Przasnysz', woj: 'mazowieckie' },
{ gmina: 'Pruszków', woj: 'mazowieckie' },
{ gmina: 'Promna', woj: 'mazowieckie' },
{ gmina: 'Prażmów', woj: 'mazowieckie' },
{ gmina: 'Potworów', woj: 'mazowieckie' },
{ gmina: 'Poświętne', woj: 'mazowieckie' },
{ gmina: 'Pomiechówek', woj: 'mazowieckie' },
{ gmina: 'Policzna', woj: 'mazowieckie' },
{ gmina: 'Pokrzywnica', woj: 'mazowieckie' },
{ gmina: 'Podkowa Leśna', woj: 'mazowieckie' },
{ gmina: 'Pniewy', woj: 'mazowieckie' },
{ gmina: 'Płońsk', woj: 'mazowieckie' },
{ gmina: 'Płoniawy-Bramura', woj: 'mazowieckie' },
{ gmina: 'Płock', woj: 'mazowieckie' },
{ gmina: 'Platerów', woj: 'mazowieckie' },
{ gmina: 'Pionki', woj: 'mazowieckie' },
{ gmina: 'Pilawa', woj: 'mazowieckie' },
{ gmina: 'Piastów', woj: 'mazowieckie' },
{ gmina: 'Piaseczno', woj: 'mazowieckie' },
{ gmina: 'Parysów', woj: 'mazowieckie' },
{ gmina: 'Paprotnia', woj: 'mazowieckie' },
{ gmina: 'Pacyna', woj: 'mazowieckie' },
{ gmina: 'Ożarów Mazowiecki', woj: 'mazowieckie' },
{ gmina: 'Otwock', woj: 'mazowieckie' },
{ gmina: 'Ostrów Mazowiecka', woj: 'mazowieckie' },
{ gmina: 'Ostrołęka', woj: 'mazowieckie' },
{ gmina: 'Osieck', woj: 'mazowieckie' },
{ gmina: 'Orońsko', woj: 'mazowieckie' },
{ gmina: 'Opinogóra Górna', woj: 'mazowieckie' },
{ gmina: 'Olszewo-Borki', woj: 'mazowieckie' },
{ gmina: 'Olszanka', woj: 'mazowieckie' },
{ gmina: 'Ojrzeń', woj: 'mazowieckie' },
{ gmina: 'Odrzywół', woj: 'mazowieckie' },
{ gmina: 'Obryte', woj: 'mazowieckie' },
{ gmina: 'Nur', woj: 'mazowieckie' },
{ gmina: 'Nowy Dwór Mazowiecki', woj: 'mazowieckie' },
{ gmina: 'Nowy Duninów', woj: 'mazowieckie' },
{ gmina: 'Nowe Miasto nad Pilicą', woj: 'mazowieckie' },
{ gmina: 'Nowe Miasto', woj: 'mazowieckie' },
{ gmina: 'Nowa Sucha', woj: 'mazowieckie' },
{ gmina: 'Nieporęt', woj: 'mazowieckie' },
{ gmina: 'Nasielsk', woj: 'mazowieckie' },
{ gmina: 'Naruszewo', woj: 'mazowieckie' },
{ gmina: 'Nadarzyn', woj: 'mazowieckie' },
{ gmina: 'Myszyniec', woj: 'mazowieckie' },
{ gmina: 'Mszczonów', woj: 'mazowieckie' },
{ gmina: 'Mrozy', woj: 'mazowieckie' },
{ gmina: 'Mordy', woj: 'mazowieckie' },
{ gmina: 'Mokobody', woj: 'mazowieckie' },
{ gmina: 'Mogielnica', woj: 'mazowieckie' },
{ gmina: 'Mochowo', woj: 'mazowieckie' },
{ gmina: 'Młynarze', woj: 'mazowieckie' },
{ gmina: 'Młodzieszyn', woj: 'mazowieckie' },
{ gmina: 'Mława', woj: 'mazowieckie' },
{ gmina: 'Mirów', woj: 'mazowieckie' },
{ gmina: 'Mińsk Mazowiecki', woj: 'mazowieckie' },
{ gmina: 'Milanówek', woj: 'mazowieckie' },
{ gmina: 'Miedzna', woj: 'mazowieckie' },
{ gmina: 'Michałowice', woj: 'mazowieckie' },
{ gmina: 'Miastków Kościelny', woj: 'mazowieckie' },
{ gmina: 'Marki', woj: 'mazowieckie' },
{ gmina: 'Małkinia Górna', woj: 'mazowieckie' },
{ gmina: 'Mała Wieś', woj: 'mazowieckie' },
{ gmina: 'Maków Mazowiecki', woj: 'mazowieckie' },
{ gmina: 'Magnuszew', woj: 'mazowieckie' },
{ gmina: 'Maciejowice', woj: 'mazowieckie' },
{ gmina: 'Łyse', woj: 'mazowieckie' },
{ gmina: 'Łosice', woj: 'mazowieckie' },
{ gmina: 'Łomianki', woj: 'mazowieckie' },
{ gmina: 'Łochów', woj: 'mazowieckie' },
{ gmina: 'Łąck', woj: 'mazowieckie' },
{ gmina: 'Łaskarzew', woj: 'mazowieckie' },
{ gmina: 'Lutocin', woj: 'mazowieckie' },
{ gmina: 'Lubowidz', woj: 'mazowieckie' },
{ gmina: 'Liw', woj: 'mazowieckie' },
{ gmina: 'Lipsko', woj: 'mazowieckie' },
{ gmina: 'Lipowiec Kościelny', woj: 'mazowieckie' },
{ gmina: 'Lesznowola', woj: 'mazowieckie' },
{ gmina: 'Leszno', woj: 'mazowieckie' },
{ gmina: 'Leoncin', woj: 'mazowieckie' },
{ gmina: 'Lelis', woj: 'mazowieckie' },
{ gmina: 'Legionowo', woj: 'mazowieckie' },
{ gmina: 'Latowicz', woj: 'mazowieckie' },
{ gmina: 'Kuczbork-Osada', woj: 'mazowieckie' },
{ gmina: 'Krzynowłoga Mała', woj: 'mazowieckie' },
{ gmina: 'Krasnosielc', woj: 'mazowieckie' },
{ gmina: 'Krasne', woj: 'mazowieckie' },
{ gmina: 'Kozienice', woj: 'mazowieckie' },
{ gmina: 'Kowala', woj: 'mazowieckie' },
{ gmina: 'Kotuń', woj: 'mazowieckie' },
{ gmina: 'Kosów Lacki', woj: 'mazowieckie' },
{ gmina: 'Korytnica', woj: 'mazowieckie' },
{ gmina: 'Korczew', woj: 'mazowieckie' },
{ gmina: 'Konstancin-Jeziorna', woj: 'mazowieckie' },
{ gmina: 'Kołbiel', woj: 'mazowieckie' },
{ gmina: 'Kobyłka', woj: 'mazowieckie' },
{ gmina: 'Klwów', woj: 'mazowieckie' },
{ gmina: 'Klembów', woj: 'mazowieckie' },
{ gmina: 'Kazanów', woj: 'mazowieckie' },
{ gmina: 'Karniewo', woj: 'mazowieckie' },
{ gmina: 'Karczew', woj: 'mazowieckie' },
{ gmina: 'Kampinos', woj: 'mazowieckie' },
{ gmina: 'Kałuszyn', woj: 'mazowieckie' },
{ gmina: 'Kadzidło', woj: 'mazowieckie' },
{ gmina: 'Józefów', woj: 'mazowieckie' },
{ gmina: 'Joniec', woj: 'mazowieckie' },
{ gmina: 'Jednorożec', woj: 'mazowieckie' },
{ gmina: 'Jedlnia-Letnisko', woj: 'mazowieckie' },
{ gmina: 'Jedlińsk', woj: 'mazowieckie' },
{ gmina: 'Jastrzębia', woj: 'mazowieckie' },
{ gmina: 'Jastrząb', woj: 'mazowieckie' },
{ gmina: 'Jasieniec', woj: 'mazowieckie' },
{ gmina: 'Jakubów', woj: 'mazowieckie' },
{ gmina: 'Jadów', woj: 'mazowieckie' },
{ gmina: 'Jabłonna Lacka', woj: 'mazowieckie' },
{ gmina: 'Jabłonna', woj: 'mazowieckie' },
{ gmina: 'Izabelin', woj: 'mazowieckie' },
{ gmina: 'Iłża', woj: 'mazowieckie' },
{ gmina: 'Iłów', woj: 'mazowieckie' },
{ gmina: 'Huszlew', woj: 'mazowieckie' },
{ gmina: 'Halinów', woj: 'mazowieckie' },
{ gmina: 'Gzy', woj: 'mazowieckie' },
{ gmina: 'Grudusk', woj: 'mazowieckie' },
{ gmina: 'Grójec', woj: 'mazowieckie' },
{ gmina: 'Grodzisk Mazowiecki', woj: 'mazowieckie' },
{ gmina: 'Grębków', woj: 'mazowieckie' },
{ gmina: 'Grabów nad Pilicą', woj: 'mazowieckie' },
{ gmina: 'Gózd', woj: 'mazowieckie' },
{ gmina: 'Górzno', woj: 'mazowieckie' },
{ gmina: 'Góra Kalwaria', woj: 'mazowieckie' },
{ gmina: 'Gozdowo', woj: 'mazowieckie' },
{ gmina: 'Goworowo', woj: 'mazowieckie' },
{ gmina: 'Goszczyn', woj: 'mazowieckie' },
{ gmina: 'Gostynin', woj: 'mazowieckie' },
{ gmina: 'Gołymin-Ośrodek', woj: 'mazowieckie' },
{ gmina: 'Gniewoszów', woj: 'mazowieckie' },
{ gmina: 'Głowaczów', woj: 'mazowieckie' },
{ gmina: 'Głowaczów', woj: 'mazowieckie' },
{ gmina: 'Glinojeck', woj: 'mazowieckie' },
{ gmina: 'Gielniów', woj: 'mazowieckie' },
{ gmina: 'Gąbin', woj: 'mazowieckie' },
{ gmina: 'Garwolin', woj: 'mazowieckie' },
{ gmina: 'Garbatka-Letnisko', woj: 'mazowieckie' },
{ gmina: 'Dzierzgowo', woj: 'mazowieckie' },
{ gmina: 'Dzierzążnia', woj: 'mazowieckie' },
{ gmina: 'Drobin', woj: 'mazowieckie' },
{ gmina: 'Domanice', woj: 'mazowieckie' },
{ gmina: 'Dobre', woj: 'mazowieckie' },
{ gmina: 'Długosiodło', woj: 'mazowieckie' },
{ gmina: 'Dębe Wielkie', woj: 'mazowieckie' },
{ gmina: 'Dąbrówka', woj: 'mazowieckie' },
{ gmina: 'Czosnów', woj: 'mazowieckie' },
{ gmina: 'Czerwonka', woj: 'mazowieckie' },
{ gmina: 'Czerwińsk nad Wisłą', woj: 'mazowieckie' },
{ gmina: 'Czerwin', woj: 'mazowieckie' },
{ gmina: 'Czernice Borowe', woj: 'mazowieckie' },
{ gmina: 'Czarnia', woj: 'mazowieckie' },
{ gmina: 'Ciepielów', woj: 'mazowieckie' },
{ gmina: 'Ciechanów', woj: 'mazowieckie' },
{ gmina: 'Chynów', woj: 'mazowieckie' },
{ gmina: 'Chotcza', woj: 'mazowieckie' },
{ gmina: 'Chorzele', woj: 'mazowieckie' },
{ gmina: 'Chlewiska', woj: 'mazowieckie' },
{ gmina: 'Ceranów', woj: 'mazowieckie' },
{ gmina: 'Celestynów', woj: 'mazowieckie' },
{ gmina: 'Cegłów', woj: 'mazowieckie' },
{ gmina: 'Bulkowo', woj: 'mazowieckie' },
{ gmina: 'Brwinów', woj: 'mazowieckie' },
{ gmina: 'Brudzeń Duży', woj: 'mazowieckie' },
{ gmina: 'Brok', woj: 'mazowieckie' },
{ gmina: 'Brochów', woj: 'mazowieckie' },
{ gmina: 'Brańszczyk', woj: 'mazowieckie' },
{ gmina: 'Borowie', woj: 'mazowieckie' },
{ gmina: 'Borkowice', woj: 'mazowieckie' },
{ gmina: 'Boguty-Pianki', woj: 'mazowieckie' },
{ gmina: 'Bodzanów', woj: 'mazowieckie' },
{ gmina: 'Błonie', woj: 'mazowieckie' },
{ gmina: 'Błędów', woj: 'mazowieckie' },
{ gmina: 'Bieżuń', woj: 'mazowieckie' },
{ gmina: 'Bielsk', woj: 'mazowieckie' },
{ gmina: 'Bielany', woj: 'mazowieckie' },
{ gmina: 'Białobrzegi', woj: 'mazowieckie' },
{ gmina: 'Belsk Duży', woj: 'mazowieckie' },
{ gmina: 'Baranów', woj: 'mazowieckie' },
{ gmina: 'Baranowo', woj: 'mazowieckie' },
{ gmina: 'Baboszewo', woj: 'mazowieckie' },
{ gmina: 'Andrzejewo', woj: 'mazowieckie' },
{ gmina: 'Złota', woj: 'świętokrzyskie' },
{ gmina: 'Zawichost', woj: 'świętokrzyskie' },
{ gmina: 'Zagnańsk', woj: 'świętokrzyskie' },
{ gmina: 'Wojciechowice', woj: 'świętokrzyskie' },
{ gmina: 'Wodzisław', woj: 'świętokrzyskie' },
{ gmina: 'Włoszczowa', woj: 'świętokrzyskie' },
{ gmina: 'Wiślica', woj: 'świętokrzyskie' },
{ gmina: 'Wilczyce', woj: 'świętokrzyskie' },
{ gmina: 'Wąchock', woj: 'świętokrzyskie' },
{ gmina: 'Waśniów', woj: 'świętokrzyskie' },
{ gmina: 'Tuczępy', woj: 'świętokrzyskie' },
{ gmina: 'Tarłów', woj: 'świętokrzyskie' },
{ gmina: 'Szydłów', woj: 'świętokrzyskie' },
{ gmina: 'Suchedniów', woj: 'świętokrzyskie' },
{ gmina: 'Strawczyn', woj: 'świętokrzyskie' },
{ gmina: 'Stopnica', woj: 'świętokrzyskie' },
{ gmina: 'Stąporków', woj: 'świętokrzyskie' },
{ gmina: 'Staszów', woj: 'świętokrzyskie' },
{ gmina: 'Starachowice', woj: 'świętokrzyskie' },
{ gmina: 'Solec-Zdrój', woj: 'świętokrzyskie' },
{ gmina: 'Sobków', woj: 'świętokrzyskie' },
{ gmina: 'Smyków', woj: 'świętokrzyskie' },
{ gmina: 'Słupia Jędrzejowska', woj: 'świętokrzyskie' },
{ gmina: 'Słupia (Konecka)', woj: 'świętokrzyskie' },
{ gmina: 'Skarżysko-Kamienna', woj: 'świętokrzyskie' },
{ gmina: 'Skarżysko Kościelne', woj: 'świętokrzyskie' },
{ gmina: 'Skalbmierz', woj: 'świętokrzyskie' },
{ gmina: 'Sitkówka-Nowiny', woj: 'świętokrzyskie' },
{ gmina: 'Sędziszów', woj: 'świętokrzyskie' },
{ gmina: 'Secemin', woj: 'świętokrzyskie' },
{ gmina: 'Sandomierz', woj: 'świętokrzyskie' },
{ gmina: 'Samborzec', woj: 'świętokrzyskie' },
{ gmina: 'Sadowie', woj: 'świętokrzyskie' },
{ gmina: 'Rytwiany', woj: 'świętokrzyskie' },
{ gmina: 'Ruda Maleniecka', woj: 'świętokrzyskie' },
{ gmina: 'Raków', woj: 'świętokrzyskie' },
{ gmina: 'Radoszyce', woj: 'świętokrzyskie' },
{ gmina: 'Radków', woj: 'świętokrzyskie' },
{ gmina: 'Połaniec', woj: 'świętokrzyskie' },
{ gmina: 'Pińczów', woj: 'świętokrzyskie' },
{ gmina: 'Pierzchnica', woj: 'świętokrzyskie' },
{ gmina: 'Piekoszów', woj: 'świętokrzyskie' },
{ gmina: 'Pawłów', woj: 'świętokrzyskie' },
{ gmina: 'Pacanów', woj: 'świętokrzyskie' },
{ gmina: 'Ożarów', woj: 'świętokrzyskie' },
{ gmina: 'Ostrowiec Świętokrzyski', woj: 'świętokrzyskie' },
{ gmina: 'Osiek', woj: 'świętokrzyskie' },
{ gmina: 'Opatów', woj: 'świętokrzyskie' },
{ gmina: 'Opatowiec', woj: 'świętokrzyskie' },
{ gmina: 'Oleśnica', woj: 'świętokrzyskie' },
{ gmina: 'Oksa', woj: 'świętokrzyskie' },
{ gmina: 'Obrazów', woj: 'świętokrzyskie' },
{ gmina: 'Nowy Korczyn', woj: 'świętokrzyskie' },
{ gmina: 'Nowa Słupia', woj: 'świętokrzyskie' },
{ gmina: 'Nagłowice', woj: 'świętokrzyskie' },
{ gmina: 'Moskorzew', woj: 'świętokrzyskie' },
{ gmina: 'Morawica', woj: 'świętokrzyskie' },
{ gmina: 'Mniów', woj: 'świętokrzyskie' },
{ gmina: 'Mirzec', woj: 'świętokrzyskie' },
{ gmina: 'Miedziana Góra', woj: 'świętokrzyskie' },
{ gmina: 'Michałów', woj: 'świętokrzyskie' },
{ gmina: 'Masłów', woj: 'świętokrzyskie' },
{ gmina: 'Małogoszcz', woj: 'świętokrzyskie' },
{ gmina: 'Łubnice', woj: 'świętokrzyskie' },
{ gmina: 'Łopuszno', woj: 'świętokrzyskie' },
{ gmina: 'Łoniów', woj: 'świętokrzyskie' },
{ gmina: 'Łączna', woj: 'świętokrzyskie' },
{ gmina: 'Łagów', woj: 'świętokrzyskie' },
{ gmina: 'Lipnik', woj: 'świętokrzyskie' },
{ gmina: 'Kunów', woj: 'świętokrzyskie' },
{ gmina: 'Krasocin', woj: 'świętokrzyskie' },
{ gmina: 'Koprzywnica', woj: 'świętokrzyskie' },
{ gmina: 'Końskie', woj: 'świętokrzyskie' },
{ gmina: 'Kluczewsko', woj: 'świętokrzyskie' },
{ gmina: 'Klimontów', woj: 'świętokrzyskie' },
{ gmina: 'Kije', woj: 'świętokrzyskie' },
{ gmina: 'Kielce', woj: 'świętokrzyskie' },
{ gmina: 'Kazimierza Wielka', woj: 'świętokrzyskie' },
{ gmina: 'Jędrzejów', woj: 'świętokrzyskie' },
{ gmina: 'Iwaniska', woj: 'świętokrzyskie' },
{ gmina: 'Imielno', woj: 'świętokrzyskie' },
{ gmina: 'Górno', woj: 'świętokrzyskie' },
{ gmina: 'Gowarczów', woj: 'świętokrzyskie' },
{ gmina: 'Gnojno', woj: 'świętokrzyskie' },
{ gmina: 'Fałków', woj: 'świętokrzyskie' },
{ gmina: 'Działoszyce', woj: 'świętokrzyskie' },
{ gmina: 'Dwikozy', woj: 'świętokrzyskie' },
{ gmina: 'Daleszyce', woj: 'świętokrzyskie' },
{ gmina: 'Ćmielów', woj: 'świętokrzyskie' },
{ gmina: 'Czarnocin', woj: 'świętokrzyskie' },
{ gmina: 'Chmielnik', woj: 'świętokrzyskie' },
{ gmina: 'Chęciny', woj: 'świętokrzyskie' },
{ gmina: 'Busko-Zdrój', woj: 'świętokrzyskie' },
{ gmina: 'Brody', woj: 'świętokrzyskie' },
{ gmina: 'Bogoria', woj: 'świętokrzyskie' },
{ gmina: 'Bodzentyn', woj: 'świętokrzyskie' },
{ gmina: 'Bodzechów', woj: 'świętokrzyskie' },
{ gmina: 'Bliżyn', woj: 'świętokrzyskie' },
{ gmina: 'Bieliny', woj: 'świętokrzyskie' },
{ gmina: 'Bejsce', woj: 'świętokrzyskie' },
{ gmina: 'Bałtów', woj: 'świętokrzyskie' },
{ gmina: 'Baćkowice', woj: 'świętokrzyskie' },
{ gmina: 'Żytno', woj: 'łódzkie' },
{ gmina: 'Żychlin', woj: 'łódzkie' },
{ gmina: 'Żelechlinek', woj: 'łódzkie' },
{ gmina: 'Żarnów', woj: 'łódzkie' },
{ gmina: 'Złoczew', woj: 'łódzkie' },
{ gmina: 'Zgierz', woj: 'łódzkie' },
{ gmina: 'Zelów', woj: 'łódzkie' },
{ gmina: 'Zduńska Wola', woj: 'łódzkie' },
{ gmina: 'Zduńska Wola', woj: 'łódzkie' },
{ gmina: 'Zduny', woj: 'łódzkie' },
{ gmina: 'Zapolice', woj: 'łódzkie' },
{ gmina: 'Zadzim', woj: 'łódzkie' },
{ gmina: 'Wróblew', woj: 'łódzkie' },
{ gmina: 'Wolbórz', woj: 'łódzkie' },
{ gmina: 'Wola Krzysztoporska', woj: 'łódzkie' },
{ gmina: 'Wodzierady', woj: 'łódzkie' },
{ gmina: 'Witonia', woj: 'łódzkie' },
{ gmina: 'Wierzchlas', woj: 'łódzkie' },
{ gmina: 'Wieruszów', woj: 'łódzkie' },
{ gmina: 'Wieluń', woj: 'łódzkie' },
{ gmina: 'Wielgomłyny', woj: 'łódzkie' },
{ gmina: 'Widawa', woj: 'łódzkie' },
{ gmina: 'Wartkowice', woj: 'łódzkie' },
{ gmina: 'Warta', woj: 'łódzkie' },
{ gmina: 'Uniejów', woj: 'łódzkie' },
{ gmina: 'Ujazd', woj: 'łódzkie' },
{ gmina: 'Tuszyn', woj: 'łódzkie' },
{ gmina: 'Tomaszów Mazowiecki', woj: 'łódzkie' },
{ gmina: 'Świnice Warckie', woj: 'łódzkie' },
{ gmina: 'Szczerców', woj: 'łódzkie' },
{ gmina: 'Szadek', woj: 'łódzkie' },
{ gmina: 'Sulmierzyce', woj: 'łódzkie' },
{ gmina: 'Sulejów', woj: 'łódzkie' },
{ gmina: 'Strzelce Wielkie', woj: 'łódzkie' },
{ gmina: 'Strzelce', woj: 'łódzkie' },
{ gmina: 'Stryków', woj: 'łódzkie' },
{ gmina: 'Sokolniki', woj: 'łódzkie' },
{ gmina: 'Słupia', woj: 'łódzkie' },
{ gmina: 'Sławno', woj: 'łódzkie' },
{ gmina: 'Skomlin', woj: 'łódzkie' },
{ gmina: 'Skierniewice', woj: 'łódzkie' },
{ gmina: 'Sieradz', woj: 'łódzkie' },
{ gmina: 'Siemkowice', woj: 'łódzkie' },
{ gmina: 'Sędziejowice', woj: 'łódzkie' },
{ gmina: 'Sadkowice', woj: 'łódzkie' },
{ gmina: 'Rzgów', woj: 'łódzkie' },
{ gmina: 'Rzeczyca', woj: 'łódzkie' },
{ gmina: 'Rząśnia', woj: 'łódzkie' },
{ gmina: 'Rusiec', woj: 'łódzkie' },
{ gmina: 'Rozprza', woj: 'łódzkie' },
{ gmina: 'Rokiciny', woj: 'łódzkie' },
{ gmina: 'Rogów', woj: 'łódzkie' },
{ gmina: 'Ręczno', woj: 'łódzkie' },
{ gmina: 'Regnów', woj: 'łódzkie' },
{ gmina: 'Rawa Mazowiecka', woj: 'łódzkie' },
{ gmina: 'Radomsko', woj: 'łódzkie' },
{ gmina: 'Przedbórz', woj: 'łódzkie' },
{ gmina: 'Poświętne', woj: 'łódzkie' },
{ gmina: 'Poddębice', woj: 'łódzkie' },
{ gmina: 'Piotrków Trybunalski', woj: 'łódzkie' },
{ gmina: 'Piątek', woj: 'łódzkie' },
{ gmina: 'Pęczniew', woj: 'łódzkie' },
{ gmina: 'Pątnów', woj: 'łódzkie' },
{ gmina: 'Parzęczew', woj: 'łódzkie' },
{ gmina: 'Paradyż', woj: 'łódzkie' },
{ gmina: 'Pajęczno', woj: 'łódzkie' },
{ gmina: 'Pabianice', woj: 'łódzkie' },
{ gmina: 'Ozorków', woj: 'łódzkie' },
{ gmina: 'Ostrówek', woj: 'łódzkie' },
{ gmina: 'Osjaków', woj: 'łódzkie' },
{ gmina: 'Oporów', woj: 'łódzkie' },
{ gmina: 'Opoczno', woj: 'łódzkie' },
{ gmina: 'Nowy Kawęczyn', woj: 'łódzkie' },
{ gmina: 'Nowosolna', woj: 'łódzkie' },
{ gmina: 'Nowe Ostrowy', woj: 'łódzkie' },
{ gmina: 'Nowa Brzeźnica', woj: 'łódzkie' },
{ gmina: 'Nieborów', woj: 'łódzkie' },
{ gmina: 'Moszczenica', woj: 'łódzkie' },
{ gmina: 'Mokrsko', woj: 'łódzkie' },
{ gmina: 'Mniszków', woj: 'łódzkie' },
{ gmina: 'Masłowice', woj: 'łódzkie' },
{ gmina: 'Maków', woj: 'łódzkie' },
{ gmina: 'Łyszkowice', woj: 'łódzkie' },
{ gmina: 'Łubnice', woj: 'łódzkie' },
{ gmina: 'Łódź', woj: 'łódzkie' },
{ gmina: 'Łowicz', woj: 'łódzkie' },
{ gmina: 'Łęki Szlacheckie', woj: 'łódzkie' },
{ gmina: 'Łęczyca', woj: 'łódzkie' },
{ gmina: 'Łask', woj: 'łódzkie' },
{ gmina: 'Łanięta', woj: 'łódzkie' },
{ gmina: 'Ładzice', woj: 'łódzkie' },
{ gmina: 'Lututów', woj: 'łódzkie' },
{ gmina: 'Lutomiersk', woj: 'łódzkie' },
{ gmina: 'Lubochnia', woj: 'łódzkie' },
{ gmina: 'Lipce Reymontowskie', woj: 'łódzkie' },
{ gmina: 'Lgota Wielka', woj: 'łódzkie' },
{ gmina: 'Kutno', woj: 'łódzkie' },
{ gmina: 'Ksawerów', woj: 'łódzkie' },
{ gmina: 'Krzyżanów', woj: 'łódzkie' },
{ gmina: 'Krośniewice', woj: 'łódzkie' },
{ gmina: 'Kowiesy', woj: 'łódzkie' },
{ gmina: 'Konstantynów Łódzki', woj: 'łódzkie' },
{ gmina: 'Konopnica', woj: 'łódzkie' },
{ gmina: 'Koluszki', woj: 'łódzkie' },
{ gmina: 'Kodrąb', woj: 'łódzkie' },
{ gmina: 'Kocierzew Południowy', woj: 'łódzkie' },
{ gmina: 'Kobiele Wielkie', woj: 'łódzkie' },
{ gmina: 'Kluki', woj: 'łódzkie' },
{ gmina: 'Klonowa', woj: 'łódzkie' },
{ gmina: 'Kleszczów', woj: 'łódzkie' },
{ gmina: 'Kiernozia', woj: 'łódzkie' },
{ gmina: 'Kiełczygłów', woj: 'łódzkie' },
{ gmina: 'Kamieńsk', woj: 'łódzkie' },
{ gmina: 'Jeżów', woj: 'łódzkie' },
{ gmina: 'Inowłódz', woj: 'łódzkie' },
{ gmina: 'Grabów', woj: 'łódzkie' },
{ gmina: 'Grabica', woj: 'łódzkie' },
{ gmina: 'Góra Świętej Małgorzaty', woj: 'łódzkie' },
{ gmina: 'Goszczanów', woj: 'łódzkie' },
{ gmina: 'Gorzkowice', woj: 'łódzkie' },
{ gmina: 'Gomunice', woj: 'łódzkie' },
{ gmina: 'Godzianów', woj: 'łódzkie' },
{ gmina: 'Głuchów', woj: 'łódzkie' },
{ gmina: 'Głowno', woj: 'łódzkie' },
{ gmina: 'Gidle', woj: 'łódzkie' },
{ gmina: 'Galewice', woj: 'łódzkie' },
{ gmina: 'Działoszyn', woj: 'łódzkie' },
{ gmina: 'Drzewica', woj: 'łódzkie' },
{ gmina: 'Drużbice', woj: 'łódzkie' },
{ gmina: 'Domaniewice', woj: 'łódzkie' },
{ gmina: 'Dobryszyce', woj: 'łódzkie' },
{ gmina: 'Dobroń', woj: 'łódzkie' },
{ gmina: 'Dmosin', woj: 'łódzkie' },
{ gmina: 'Dłutów', woj: 'łódzkie' },
{ gmina: 'Dąbrowice', woj: 'łódzkie' },
{ gmina: 'Daszyna', woj: 'łódzkie' },
{ gmina: 'Dalików', woj: 'łódzkie' },
{ gmina: 'Czerniewice', woj: 'łódzkie' },
{ gmina: 'Czastary', woj: 'łódzkie' },
{ gmina: 'Czarnożyły', woj: 'łódzkie' },
{ gmina: 'Czarnocin', woj: 'łódzkie' },
{ gmina: 'Cielądz', woj: 'łódzkie' },
{ gmina: 'Chąśno', woj: 'łódzkie' },
{ gmina: 'Burzenin', woj: 'łódzkie' },
{ gmina: 'Budziszewice', woj: 'łódzkie' },
{ gmina: 'Buczek', woj: 'łódzkie' },
{ gmina: 'Brzeźnio', woj: 'łódzkie' },
{ gmina: 'Brójce', woj: 'łódzkie' },
{ gmina: 'Brąszewice', woj: 'łódzkie' },
{ gmina: 'Bolimów', woj: 'łódzkie' },
{ gmina: 'Bolesławiec', woj: 'łódzkie' },
{ gmina: 'Błaszki', woj: 'łódzkie' },
{ gmina: 'Bielawy', woj: 'łódzkie' },
{ gmina: 'Białaczów', woj: 'łódzkie' },
{ gmina: 'Biała Rawska', woj: 'łódzkie' },
{ gmina: 'Biała', woj: 'łódzkie' },
{ gmina: 'Będków', woj: 'łódzkie' },
{ gmina: 'Bełchatów', woj: 'łódzkie' },
{ gmina: 'Bedlno', woj: 'łódzkie' },
{ gmina: 'Andrespol', woj: 'łódzkie' },
{ gmina: 'Aleksandrów Łódzki', woj: 'łódzkie' },
{ gmina: 'Aleksandrów', woj: 'łódzkie' },
{ gmina: 'Zębowice', woj: 'opolskie' },
{ gmina: 'Zdzieszowice', woj: 'opolskie' },
{ gmina: 'Zawadzkie', woj: 'opolskie' },
{ gmina: 'Wołczyn', woj: 'opolskie' },
{ gmina: 'Wilków', woj: 'opolskie' },
{ gmina: 'Walce', woj: 'opolskie' },
{ gmina: 'Ujazd', woj: 'opolskie' },
{ gmina: 'Turawa', woj: 'opolskie' },
{ gmina: 'Tułowice', woj: 'opolskie' },
{ gmina: 'Tarnów Opolski', woj: 'opolskie' },
{ gmina: 'Świerczów', woj: 'opolskie' },
{ gmina: 'Strzeleczki', woj: 'opolskie' },
{ gmina: 'Strzelce Opolskie', woj: 'opolskie' },
{ gmina: 'Skoroszyce', woj: 'opolskie' },
{ gmina: 'Skarbimierz', woj: 'opolskie' },
{ gmina: 'Rudniki', woj: 'opolskie' },
{ gmina: 'Reńska Wieś', woj: 'opolskie' },
{ gmina: 'Radłów', woj: 'opolskie' },
{ gmina: 'Prudnik', woj: 'opolskie' },
{ gmina: 'Prószków', woj: 'opolskie' },
{ gmina: 'Praszka', woj: 'opolskie' },
{ gmina: 'Popielów', woj: 'opolskie' },
{ gmina: 'Polska Cerekiew', woj: 'opolskie' },
{ gmina: 'Pokój', woj: 'opolskie' },
{ gmina: 'Pawłowiczki', woj: 'opolskie' },
{ gmina: 'Pakosławice', woj: 'opolskie' },
{ gmina: 'Paczków', woj: 'opolskie' },
{ gmina: 'Ozimek', woj: 'opolskie' },
{ gmina: 'Otmuchów', woj: 'opolskie' },
{ gmina: 'Opole', woj: 'opolskie' },
{ gmina: 'Olszanka', woj: 'opolskie' },
{ gmina: 'Olesno', woj: 'opolskie' },
{ gmina: 'Nysa', woj: 'opolskie' },
{ gmina: 'Niemodlin', woj: 'opolskie' },
{ gmina: 'Namysłów', woj: 'opolskie' },
{ gmina: 'Murów', woj: 'opolskie' },
{ gmina: 'Łubniany', woj: 'opolskie' },
{ gmina: 'Łambinowice', woj: 'opolskie' },
{ gmina: 'Lubsza', woj: 'opolskie' },
{ gmina: 'Lubrza', woj: 'opolskie' },
{ gmina: 'Lewin Brzeski', woj: 'opolskie' },
{ gmina: 'Leśnica', woj: 'opolskie' },
{ gmina: 'Lasowice Wielkie', woj: 'opolskie' },
{ gmina: 'Krapkowice', woj: 'opolskie' },
{ gmina: 'Korfantów', woj: 'opolskie' },
{ gmina: 'Komprachcice', woj: 'opolskie' },
{ gmina: 'Kolonowskie', woj: 'opolskie' },
{ gmina: 'Kluczbork', woj: 'opolskie' },
{ gmina: 'Kietrz', woj: 'opolskie' },
{ gmina: 'Kędzierzyn-Koźle', woj: 'opolskie' },
{ gmina: 'Kamiennik', woj: 'opolskie' },
{ gmina: 'Jemielnica', woj: 'opolskie' },
{ gmina: 'Izbicko', woj: 'opolskie' },
{ gmina: 'Grodków', woj: 'opolskie' },
{ gmina: 'Gorzów Śląski', woj: 'opolskie' },
{ gmina: 'Gogolin', woj: 'opolskie' },
{ gmina: 'Głuchołazy', woj: 'opolskie' },
{ gmina: 'Głubczyce', woj: 'opolskie' },
{ gmina: 'Głogówek', woj: 'opolskie' },
{ gmina: 'Domaszowice', woj: 'opolskie' },
{ gmina: 'Dobrzeń Wielki', woj: 'opolskie' },
{ gmina: 'Dobrodzień', woj: 'opolskie' },
{ gmina: 'Dąbrowa', woj: 'opolskie' },
{ gmina: 'Cisek', woj: 'opolskie' },
{ gmina: 'Chrząstowice', woj: 'opolskie' },
{ gmina: 'Byczyna', woj: 'opolskie' },
{ gmina: 'Brzeg', woj: 'opolskie' },
{ gmina: 'Branice', woj: 'opolskie' },
{ gmina: 'Bierawa', woj: 'opolskie' },
{ gmina: 'Biała', woj: 'opolskie' },
{ gmina: 'Baborów', woj: 'opolskie' },
{ gmina: 'Żywiec', woj: 'śląskie' },
{ gmina: 'Żory', woj: 'śląskie' },
{ gmina: 'Żarnowiec', woj: 'śląskie' },
{ gmina: 'Żarki', woj: 'śląskie' },
{ gmina: 'Zebrzydowice', woj: 'śląskie' },
{ gmina: 'Zbrosławice', woj: 'śląskie' },
{ gmina: 'Zawiercie', woj: 'śląskie' },
{ gmina: 'Zabrze', woj: 'śląskie' },
{ gmina: 'Wyry', woj: 'śląskie' },
{ gmina: 'Wręczyca Wielka', woj: 'śląskie' },
{ gmina: 'Woźniki', woj: 'śląskie' },
{ gmina: 'Wojkowice', woj: 'śląskie' },
{ gmina: 'Wodzisław Śląski', woj: 'śląskie' },
{ gmina: 'Włodowice', woj: 'śląskie' },
{ gmina: 'Wisła', woj: 'śląskie' },
{ gmina: 'Wilkowice', woj: 'śląskie' },
{ gmina: 'Wilamowice', woj: 'śląskie' },
{ gmina: 'Wielowieś', woj: 'śląskie' },
{ gmina: 'Węgierska Górka', woj: 'śląskie' },
{ gmina: 'Ustroń', woj: 'śląskie' },
{ gmina: 'Ujsoły', woj: 'śląskie' },
{ gmina: 'Tychy', woj: 'śląskie' },
{ gmina: 'Tworóg', woj: 'śląskie' },
{ gmina: 'Toszek', woj: 'śląskie' },
{ gmina: 'Tarnowskie Góry', woj: 'śląskie' },
{ gmina: 'Świnna', woj: 'śląskie' },
{ gmina: 'Świętochłowice', woj: 'śląskie' },
{ gmina: 'Świerklany', woj: 'śląskie' },
{ gmina: 'Świerklaniec', woj: 'śląskie' },
{ gmina: 'Ślemień', woj: 'śląskie' },
{ gmina: 'Szczyrk', woj: 'śląskie' },
{ gmina: 'Szczekociny', woj: 'śląskie' },
{ gmina: 'Suszec', woj: 'śląskie' },
{ gmina: 'Strumień', woj: 'śląskie' },
{ gmina: 'Starcza', woj: 'śląskie' },
{ gmina: 'Sośnicowice', woj: 'śląskie' },
{ gmina: 'Sosnowiec', woj: 'śląskie' },
{ gmina: 'Sławków', woj: 'śląskie' },
{ gmina: 'Skoczów', woj: 'śląskie' },
{ gmina: 'Siewierz', woj: 'śląskie' },
{ gmina: 'Siemianowice Śląskie', woj: 'śląskie' },
{ gmina: 'Rydułtowy', woj: 'śląskie' },
{ gmina: 'Rybnik', woj: 'śląskie' },
{ gmina: 'Rudziniec', woj: 'śląskie' },
{ gmina: 'Rudnik', woj: 'śląskie' },
{ gmina: 'Ruda Śląska', woj: 'śląskie' },
{ gmina: 'Rędziny', woj: 'śląskie' },
{ gmina: 'Rajcza', woj: 'śląskie' },
{ gmina: 'Radzionków', woj: 'śląskie' },
{ gmina: 'Radziechowy-Wieprz', woj: 'śląskie' },
{ gmina: 'Radlin', woj: 'śląskie' },
{ gmina: 'Racibórz', woj: 'śląskie' },
{ gmina: 'Pyskowice', woj: 'śląskie' },
{ gmina: 'Pszów', woj: 'śląskie' },
{ gmina: 'Pszczyna', woj: 'śląskie' },
{ gmina: 'Psary', woj: 'śląskie' },
{ gmina: 'Przystajń', woj: 'śląskie' },
{ gmina: 'Przyrów', woj: 'śląskie' },
{ gmina: 'Poręba', woj: 'śląskie' },
{ gmina: 'Porąbka', woj: 'śląskie' },
{ gmina: 'Poraj', woj: 'śląskie' },
{ gmina: 'Popów', woj: 'śląskie' },
{ gmina: 'Poczesna', woj: 'śląskie' },
{ gmina: 'Pilica', woj: 'śląskie' },
{ gmina: 'Pilchowice', woj: 'śląskie' },
{ gmina: 'Pietrowice Wielkie', woj: 'śląskie' },
{ gmina: 'Piekary Śląskie', woj: 'śląskie' },
{ gmina: 'Pawonków', woj: 'śląskie' },
{ gmina: 'Pawłowice', woj: 'śląskie' },
{ gmina: 'Panki', woj: 'śląskie' },
{ gmina: 'Ożarowice', woj: 'śląskie' },
{ gmina: 'Orzesze', woj: 'śląskie' },
{ gmina: 'Ornontowice', woj: 'śląskie' },
{ gmina: 'Opatów', woj: 'śląskie' },
{ gmina: 'Olsztyn', woj: 'śląskie' },
{ gmina: 'Ogrodzieniec', woj: 'śląskie' },
{ gmina: 'Niegowa', woj: 'śląskie' },
{ gmina: 'Nędza', woj: 'śląskie' },
{ gmina: 'Myszków', woj: 'śląskie' },
{ gmina: 'Mysłowice', woj: 'śląskie' },
{ gmina: 'Mykanów', woj: 'śląskie' },
{ gmina: 'Mszana', woj: 'śląskie' },
{ gmina: 'Mstów', woj: 'śląskie' },
{ gmina: 'Milówka', woj: 'śląskie' },
{ gmina: 'Mikołów', woj: 'śląskie' },
{ gmina: 'Mierzęcice', woj: 'śląskie' },
{ gmina: 'Miedźno', woj: 'śląskie' },
{ gmina: 'Miedźna', woj: 'śląskie' },
{ gmina: 'Miasteczko Śląskie', woj: 'śląskie' },
{ gmina: 'Marklowice', woj: 'śląskie' },
{ gmina: 'Łodygowice', woj: 'śląskie' },
{ gmina: 'Łękawica', woj: 'śląskie' },
{ gmina: 'Łazy', woj: 'śląskie' },
{ gmina: 'Łazy', woj: 'śląskie' },
{ gmina: 'Łaziska Górne', woj: 'śląskie' },
{ gmina: 'Lyski', woj: 'śląskie' },
{ gmina: 'Lubomia', woj: 'śląskie' },
{ gmina: 'Lubliniec', woj: 'śląskie' },
{ gmina: 'Lipowa', woj: 'śląskie' },
{ gmina: 'Lipie', woj: 'śląskie' },
{ gmina: 'Lędziny', woj: 'śląskie' },
{ gmina: 'Lelów', woj: 'śląskie' },
{ gmina: 'Kuźnia Raciborska', woj: 'śląskie' },
{ gmina: 'Krzyżanowice', woj: 'śląskie' },
{ gmina: 'Krzepice', woj: 'śląskie' },
{ gmina: 'Krzanowice', woj: 'śląskie' },
{ gmina: 'Kruszyna', woj: 'śląskie' },
{ gmina: 'Krupski Młyn', woj: 'śląskie' },
{ gmina: 'Kroczyce', woj: 'śląskie' },
{ gmina: 'Kozy', woj: 'śląskie' },
{ gmina: 'Koziegłowy', woj: 'śląskie' },
{ gmina: 'Koszęcin', woj: 'śląskie' },
{ gmina: 'Koszarawa', woj: 'śląskie' },
{ gmina: 'Kornowac', woj: 'śląskie' },
{ gmina: 'Konopiska', woj: 'śląskie' },
{ gmina: 'Koniecpol', woj: 'śląskie' },
{ gmina: 'Kochanowice', woj: 'śląskie' },
{ gmina: 'Kobiór', woj: 'śląskie' },
{ gmina: 'Knurów', woj: 'śląskie' },
{ gmina: 'Kłomnice', woj: 'śląskie' },
{ gmina: 'Kłobuck', woj: 'śląskie' },
{ gmina: 'Katowice', woj: 'śląskie' },
{ gmina: 'Kamienica Polska', woj: 'śląskie' },
{ gmina: 'Kalety', woj: 'śląskie' },
{ gmina: 'Jeleśnia', woj: 'śląskie' },
{ gmina: 'Jejkowice', woj: 'śląskie' },
{ gmina: 'Jaworze', woj: 'śląskie' },
{ gmina: 'Jastrzębie Zdrój', woj: 'śląskie' },
{ gmina: 'Jasienica', woj: 'śląskie' },
{ gmina: 'Janów', woj: 'śląskie' },
{ gmina: 'Istebna', woj: 'śląskie' },
{ gmina: 'Irządze', woj: 'śląskie' },
{ gmina: 'Imielin', woj: 'śląskie' },
{ gmina: 'Herby', woj: 'śląskie' },
{ gmina: 'Hażlach', woj: 'śląskie' },
{ gmina: 'Gorzyce', woj: 'śląskie' },
{ gmina: 'Goleszów', woj: 'śląskie' },
{ gmina: 'Godów', woj: 'śląskie' },
{ gmina: 'Goczałkowice-Zdrój', woj: 'śląskie' },
{ gmina: 'Gliwice', woj: 'śląskie' },
{ gmina: 'Gilowice', woj: 'śląskie' },
{ gmina: 'Gierałtowice', woj: 'śląskie' },
{ gmina: 'Gaszowice', woj: 'śląskie' },
{ gmina: 'Dębowiec', woj: 'śląskie' },
{ gmina: 'Dąbrowa Zielona', woj: 'śląskie' },
{ gmina: 'Dąbrowa Górnicza', woj: 'śląskie' },
{ gmina: 'Częstochowa', woj: 'śląskie' },
{ gmina: 'Czerwionka-Leszczyny', woj: 'śląskie' },
{ gmina: 'Czernichów', woj: 'śląskie' },
{ gmina: 'Czeladź', woj: 'śląskie' },
{ gmina: 'Czechowice-Dziedzice', woj: 'śląskie' },
{ gmina: 'Cieszyn', woj: 'śląskie' },
{ gmina: 'Ciasna', woj: 'śląskie' },
{ gmina: 'Chybie', woj: 'śląskie' },
{ gmina: 'Chorzów', woj: 'śląskie' },
{ gmina: 'Chełm Śląski', woj: 'śląskie' },
{ gmina: 'Bytom', woj: 'śląskie' },
{ gmina: 'Buczkowice', woj: 'śląskie' },
{ gmina: 'Brenna', woj: 'śląskie' },
{ gmina: 'Boronów', woj: 'śląskie' },
{ gmina: 'Bojszowy', woj: 'śląskie' },
{ gmina: 'Bobrowniki', woj: 'śląskie' },
{ gmina: 'Blachownia', woj: 'śląskie' },
{ gmina: 'Bieruń', woj: 'śląskie' },
{ gmina: 'Bielsko-Biała', woj: 'śląskie' },
{ gmina: 'Będzin', woj: 'śląskie' },
{ gmina: 'Bestwina', woj: 'śląskie' },
{ gmina: 'Żegocina', woj: 'małopolskie' },
{ gmina: 'Żabno', woj: 'małopolskie' },
{ gmina: 'Zielonki', woj: 'małopolskie' },
{ gmina: 'Zembrzyce', woj: 'małopolskie' },
{ gmina: 'Zawoja', woj: 'małopolskie' },
{ gmina: 'Zator', woj: 'małopolskie' },
{ gmina: 'Zakopane', woj: 'małopolskie' },
{ gmina: 'Zakliczyn', woj: 'małopolskie' },
{ gmina: 'Zabierzów', woj: 'małopolskie' },
{ gmina: 'Wolbrom', woj: 'małopolskie' },
{ gmina: 'Wojnicz', woj: 'małopolskie' },
{ gmina: 'Wiśniowa', woj: 'małopolskie' },
{ gmina: 'Wietrzychowice', woj: 'małopolskie' },
{ gmina: 'Wierzchosławice', woj: 'małopolskie' },
{ gmina: 'Wieprz', woj: 'małopolskie' },
{ gmina: 'Wielka Wieś', woj: 'małopolskie' },
{ gmina: 'Wieliczka', woj: 'małopolskie' },
{ gmina: 'Wadowice', woj: 'małopolskie' },
{ gmina: 'Uście Gorlickie', woj: 'małopolskie' },
{ gmina: 'Tymbark', woj: 'małopolskie' },
{ gmina: 'Tuchów', woj: 'małopolskie' },
{ gmina: 'Trzyciąż', woj: 'małopolskie' },
{ gmina: 'Trzebinia', woj: 'małopolskie' },
{ gmina: 'Trzciana', woj: 'małopolskie' },
{ gmina: 'Tomice', woj: 'małopolskie' },
{ gmina: 'Tokarnia', woj: 'małopolskie' },
{ gmina: 'Tarnów', woj: 'małopolskie' },
{ gmina: 'Świątniki Górne', woj: 'małopolskie' },
{ gmina: 'Szerzyny', woj: 'małopolskie' },
{ gmina: 'Szczurowa', woj: 'małopolskie' },
{ gmina: 'Szczucin', woj: 'małopolskie' },
{ gmina: 'Szczawnica', woj: 'małopolskie' },
{ gmina: 'Szaflary', woj: 'małopolskie' },
{ gmina: 'Sułoszowa', woj: 'małopolskie' },
{ gmina: 'Sułkowice', woj: 'małopolskie' },
{ gmina: 'Sucha Beskidzka', woj: 'małopolskie' },
{ gmina: 'Stryszów', woj: 'małopolskie' },
{ gmina: 'Stryszawa', woj: 'małopolskie' },
{ gmina: 'Stary Sącz', woj: 'małopolskie' },
{ gmina: 'Spytkowice - powiat nowotarski', woj: 'małopolskie' },
{ gmina: 'Spytkowice - powiat wadowicki', woj: 'małopolskie' },
{ gmina: 'Słopnice', woj: 'małopolskie' },
{ gmina: 'Słomniki', woj: 'małopolskie' },
{ gmina: 'Słaboszów', woj: 'małopolskie' },
{ gmina: 'Skrzyszów', woj: 'małopolskie' },
{ gmina: 'Skawina', woj: 'małopolskie' },
{ gmina: 'Skała', woj: 'małopolskie' },
{ gmina: 'Siepraw', woj: 'małopolskie' },
{ gmina: 'Sękowa', woj: 'małopolskie' },
{ gmina: 'Rzezawa', woj: 'małopolskie' },
{ gmina: 'Rzepiennik Strzyżewski', woj: 'małopolskie' },
{ gmina: 'Rytro', woj: 'małopolskie' },
{ gmina: 'Ryglice', woj: 'małopolskie' },
{ gmina: 'Ropa', woj: 'małopolskie' },
{ gmina: 'Radziemice', woj: 'małopolskie' },
{ gmina: 'Radłów', woj: 'małopolskie' },
{ gmina: 'Radgoszcz', woj: 'małopolskie' },
{ gmina: 'Racławice', woj: 'małopolskie' },
{ gmina: 'Raciechowice', woj: 'małopolskie' },
{ gmina: 'Rabka-Zdrój', woj: 'małopolskie' },
{ gmina: 'Raba Wyżna', woj: 'małopolskie' },
{ gmina: 'Przeciszów', woj: 'małopolskie' },
{ gmina: 'Proszowice', woj: 'małopolskie' },
{ gmina: 'Poronin', woj: 'małopolskie' },
{ gmina: 'Polanka Wielka', woj: 'małopolskie' },
{ gmina: 'Podegrodzie', woj: 'małopolskie' },
{ gmina: 'Pleśna', woj: 'małopolskie' },
{ gmina: 'Piwniczna-Zdrój', woj: 'małopolskie' },
{ gmina: 'Pcim', woj: 'małopolskie' },
{ gmina: 'Pałecznica', woj: 'małopolskie' },
{ gmina: 'Oświęcim', woj: 'małopolskie' },
{ gmina: 'Osiek', woj: 'małopolskie' },
{ gmina: 'Olkusz', woj: 'małopolskie' },
{ gmina: 'Olesno', woj: 'małopolskie' },
{ gmina: 'Ochotnica Dolna', woj: 'małopolskie' },
{ gmina: 'Nowy Wiśnicz', woj: 'małopolskie' },
{ gmina: 'Nowy Targ', woj: 'małopolskie' },
{ gmina: 'Nowy Sącz', woj: 'małopolskie' },
{ gmina: 'Nowe Brzesko', woj: 'małopolskie' },
{ gmina: 'Niepołomice', woj: 'małopolskie' },
{ gmina: 'Niedźwiedź', woj: 'małopolskie' },
{ gmina: 'Nawojowa', woj: 'małopolskie' },
{ gmina: 'Myślenice', woj: 'małopolskie' },
{ gmina: 'Muszyna', woj: 'małopolskie' },
{ gmina: 'Mucharz', woj: 'małopolskie' },
{ gmina: 'Mszana Dolna', woj: 'małopolskie' },
{ gmina: 'Moszczenica', woj: 'małopolskie' },
{ gmina: 'Mogilany', woj: 'małopolskie' },
{ gmina: 'Miechów', woj: 'małopolskie' },
{ gmina: 'Michałowice', woj: 'małopolskie' },
{ gmina: 'Mędrzechów', woj: 'małopolskie' },
{ gmina: 'Maków Podhalański', woj: 'małopolskie' },
{ gmina: 'Łużna', woj: 'małopolskie' },
{ gmina: 'Łukowica', woj: 'małopolskie' },
{ gmina: 'Łososina Dolna', woj: 'małopolskie' },
{ gmina: 'Łącko', woj: 'małopolskie' },
{ gmina: 'Łapsze Niżne', woj: 'małopolskie' },
{ gmina: 'Łapanów', woj: 'małopolskie' },
{ gmina: 'Łabowa', woj: 'małopolskie' },
{ gmina: 'Lubień', woj: 'małopolskie' },
{ gmina: 'Liszki', woj: 'małopolskie' },
{ gmina: 'Lisia Góra', woj: 'małopolskie' },
{ gmina: 'Lipnica Wielka', woj: 'małopolskie' },
{ gmina: 'Lipnica Murowana', woj: 'małopolskie' },
{ gmina: 'Lipinki', woj: 'małopolskie' },
{ gmina: 'Limanowa', woj: 'małopolskie' },
{ gmina: 'Libiąż', woj: 'małopolskie' },
{ gmina: 'Laskowa', woj: 'małopolskie' },
{ gmina: 'Lanckorona', woj: 'małopolskie' },
{ gmina: 'Książ Wielki', woj: 'małopolskie' },
{ gmina: 'Krzeszowice', woj: 'małopolskie' },
{ gmina: 'Krynica-Zdrój', woj: 'małopolskie' },
{ gmina: 'Krościenko nad Dunajcem', woj: 'małopolskie' },
{ gmina: 'Kraków', woj: 'małopolskie' },
{ gmina: 'Kozłów', woj: 'małopolskie' },
{ gmina: 'Kościelisko', woj: 'małopolskie' },
{ gmina: 'Koszyce', woj: 'małopolskie' },
{ gmina: 'Korzenna', woj: 'małopolskie' },
{ gmina: 'Koniusza', woj: 'małopolskie' },
{ gmina: 'Kocmyrzów-Luborzyca', woj: 'małopolskie' },
{ gmina: 'Kłaj', woj: 'małopolskie' },
{ gmina: 'Klucze', woj: 'małopolskie' },
{ gmina: 'Kęty', woj: 'małopolskie' },
{ gmina: 'Kamionka Wielka', woj: 'małopolskie' },
{ gmina: 'Kamienica', woj: 'małopolskie' },
{ gmina: 'Kalwaria Zebrzydowska', woj: 'małopolskie' },
{ gmina: 'Jordanów', woj: 'małopolskie' },
{ gmina: 'Jerzmanowice-Przeginia', woj: 'małopolskie' },
{ gmina: 'Jabłonka', woj: 'małopolskie' },
{ gmina: 'Iwkowa', woj: 'małopolskie' },
{ gmina: 'Iwanowice', woj: 'małopolskie' },
{ gmina: 'Igołomia-Wawrzeńczyce', woj: 'małopolskie' },
{ gmina: 'Grybów', woj: 'małopolskie' },
{ gmina: 'Gródek nad Dunajcem', woj: 'małopolskie' },
{ gmina: 'Gromnik', woj: 'małopolskie' },
{ gmina: 'Gręboszów', woj: 'małopolskie' },
{ gmina: 'Gorlice', woj: 'małopolskie' },
{ gmina: 'Gołcza', woj: 'małopolskie' },
{ gmina: 'Gnojnik', woj: 'małopolskie' },
{ gmina: 'Gdów', woj: 'małopolskie' },
{ gmina: 'Drwinia', woj: 'małopolskie' },
{ gmina: 'Dobra', woj: 'małopolskie' },
{ gmina: 'Dobczyce', woj: 'małopolskie' },
{ gmina: 'Dębno', woj: 'małopolskie' },
{ gmina: 'Dąbrowa Tarnowska', woj: 'małopolskie' },
{ gmina: 'Czorsztyn', woj: 'małopolskie' },
{ gmina: 'Czernichów', woj: 'małopolskie' },
{ gmina: 'Czchów', woj: 'małopolskie' },
{ gmina: 'Czarny Dunajec', woj: 'małopolskie' },
{ gmina: 'Ciężkowice', woj: 'małopolskie' },
{ gmina: 'Chrzanów', woj: 'małopolskie' },
{ gmina: 'Chełmiec', woj: 'małopolskie' },
{ gmina: 'Chełmek', woj: 'małopolskie' },
{ gmina: 'Charsznica', woj: 'małopolskie' },
{ gmina: 'Bystra-Sidzina', woj: 'małopolskie' },
{ gmina: 'Bukowno', woj: 'małopolskie' },
{ gmina: 'Bukowina Tatrzańska', woj: 'małopolskie' },
{ gmina: 'Budzów', woj: 'małopolskie' },
{ gmina: 'Brzeźnica', woj: 'małopolskie' },
{ gmina: 'Brzeszcze', woj: 'małopolskie' },
{ gmina: 'Brzesko', woj: 'małopolskie' },
{ gmina: 'Borzęcin', woj: 'małopolskie' },
{ gmina: 'Bolesław - powiat dąbrowski', woj: 'małopolskie' },
{ gmina: 'Bolesław', woj: 'małopolskie' },
{ gmina: 'Bochnia', woj: 'małopolskie' },
{ gmina: 'Bobowa', woj: 'małopolskie' },
{ gmina: 'Biskupice', woj: 'małopolskie' },
{ gmina: 'Biały Dunajec', woj: 'małopolskie' },
{ gmina: 'Biecz', woj: 'małopolskie' },
{ gmina: 'Babice', woj: 'małopolskie' },
{ gmina: 'Andrychów', woj: 'małopolskie' },
{ gmina: 'Alwernia', woj: 'małopolskie' },
{ gmina: 'Besko', woj: 'podkarpackie' },
{ gmina: 'Białobrzegi', woj: 'podkarpackie' },
{ gmina: 'Boguchwała', woj: 'podkarpackie' },
{ gmina: 'Borowa', woj: 'podkarpackie' },
{ gmina: 'Brzostek', woj: 'podkarpackie' },
{ gmina: 'Brzyska', woj: 'podkarpackie' },
{ gmina: 'Chłopice', woj: 'podkarpackie' },
{ gmina: 'Cieszanów', woj: 'podkarpackie' },
{ gmina: 'Czarna', woj: 'podkarpackie' },
{ gmina: 'Dębica', woj: 'podkarpackie' },
{ gmina: 'Dubiecko', woj: 'podkarpackie' },
{ gmina: 'Dydnia', woj: 'podkarpackie' },
{ gmina: 'Dynów', woj: 'podkarpackie' },
{ gmina: 'Fredropol', woj: 'podkarpackie' },
{ gmina: 'Frysztak', woj: 'podkarpackie' },
{ gmina: 'Gać', woj: 'podkarpackie' },
{ gmina: 'Gawłuszowice', woj: 'podkarpackie' },
{ gmina: 'Gorzyce', woj: 'podkarpackie' },
{ gmina: 'Grodzisko Dolne', woj: 'podkarpackie' },
{ gmina: 'Horyniec-Zdrój', woj: 'podkarpackie' },
{ gmina: 'Iwierzyce', woj: 'podkarpackie' },
{ gmina: 'Jarosław', woj: 'podkarpackie' },
{ gmina: 'Jasienica Rosielna', woj: 'podkarpackie' },
{ gmina: 'Kamień', woj: 'podkarpackie' },
{ gmina: 'Kańczuga', woj: 'podkarpackie' },
{ gmina: 'Korczyna', woj: 'podkarpackie' },
{ gmina: 'Krasne', woj: 'podkarpackie' },
{ gmina: 'Krościenko Wyżne', woj: 'podkarpackie' },
{ gmina: 'Krzeszów', woj: 'podkarpackie' },
{ gmina: 'Laszki', woj: 'podkarpackie' },
{ gmina: 'Leżajsk', woj: 'podkarpackie' },
{ gmina: 'Lubaczów', woj: 'podkarpackie' },
{ gmina: 'Lubenia', woj: 'podkarpackie' },
{ gmina: 'Łańcut', woj: 'podkarpackie' },
{ gmina: 'Majdan Królewski', woj: 'podkarpackie' },
{ gmina: 'Markowa', woj: 'podkarpackie' },
{ gmina: 'Medyka', woj: 'podkarpackie' },
{ gmina: 'Mielec', woj: 'podkarpackie' },
{ gmina: 'Narol', woj: 'podkarpackie' },
{ gmina: 'Nozdrzec', woj: 'podkarpackie' },
{ gmina: 'Oleszyce', woj: 'podkarpackie' },
{ gmina: 'Orły', woj: 'podkarpackie' },
{ gmina: 'Ostrów', woj: 'podkarpackie' },
{ gmina: 'Padew Narodowa', woj: 'podkarpackie' },
{ gmina: 'Pawłosiów', woj: 'podkarpackie' },
{ gmina: 'Pilzno', woj: 'podkarpackie' },
{ gmina: 'Pruchnik', woj: 'podkarpackie' },
{ gmina: 'Przecław', woj: 'podkarpackie' },
{ gmina: 'Przemyśl', woj: 'podkarpackie' },
{ gmina: 'Przeworsk', woj: 'podkarpackie' },
{ gmina: 'Radomyśl nad Sanem', woj: 'podkarpackie' },
{ gmina: 'Radomyśl Wielki', woj: 'podkarpackie' },
{ gmina: 'Radymno', woj: 'podkarpackie' },
{ gmina: 'Rokietnica', woj: 'podkarpackie' },
{ gmina: 'Ropczyce', woj: 'podkarpackie' },
{ gmina: 'Roźwienica', woj: 'podkarpackie' },
{ gmina: 'Rymanów', woj: 'podkarpackie' },
{ gmina: 'Rzeszów', woj: 'podkarpackie' },
{ gmina: 'Sędziszów Małopolski', woj: 'podkarpackie' },
{ gmina: 'Sieniawa', woj: 'podkarpackie' },
{ gmina: 'Stalowa Wola', woj: 'podkarpackie' },
{ gmina: 'Strzyżów', woj: 'podkarpackie' },
{ gmina: 'Stubno', woj: 'podkarpackie' },
{ gmina: 'Świlcza', woj: 'podkarpackie' },
{ gmina: 'Tarnobrzeg', woj: 'podkarpackie' },
{ gmina: 'Tryńcza', woj: 'podkarpackie' },
{ gmina: 'Trzebownisko', woj: 'podkarpackie' },
{ gmina: 'Tyczyn', woj: 'podkarpackie' },
{ gmina: 'Wadowice Górne', woj: 'podkarpackie' },
{ gmina: 'Wiązownica', woj: 'podkarpackie' },
{ gmina: 'Wielkie Oczy', woj: 'podkarpackie' },
{ gmina: 'Wielopole Skrzyńskie', woj: 'podkarpackie' },
{ gmina: 'Wiśniowa', woj: 'podkarpackie' },
{ gmina: 'Zaklików', woj: 'podkarpackie' },
{ gmina: 'Zarszyn', woj: 'podkarpackie' },
{ gmina: 'Zarzecze', woj: 'podkarpackie' },
{ gmina: 'Żołynia', woj: 'podkarpackie' },
{ gmina: 'Żurawica', woj: 'podkarpackie' },
{ gmina: 'Żyraków', woj: 'podkarpackie' }
];
